import { describe, expect, it } from 'vitest';
import type { Repo } from '../repo';
import { seedData } from '../seed';
import type { Certificate, CourseTemplate, Program, Requirement, Rubric, DesignSession, InstructorProfile } from '../domain';
import type { StoredReadinessItem } from '../repo';

/** Shared behavioral contract for MemoryRepo and the Worker's D1Repo. */
export function describeRepoContract(name: string, makeRepo: () => Promise<Repo>) {
  describe(name, () => {
    it('lists the same seed files after reset', async () => {
      const repo = await makeRepo();
      expect(await repo.listFiles('c-stat110')).toEqual(seedData().files.filter(file => file.courseId === 'c-stat110'));
      await repo.reset(seedData());
      expect(await repo.listFiles('c-stat110')).toEqual(seedData().files.filter(file => file.courseId === 'c-stat110'));
    });
    it('rejects an options claim with a duplicate job id without changing the session', async () => {
      const repo = await makeRepo();
      const at = '2026-09-28T12:00:00Z';
      const session = { id: 'ds-duplicate-options', courseId: 'c-stat110', mode: 'syllabus', stage: 'read', createdBy: 'u-okafor', createdAt: at, updatedAt: at,
        source: { kind: 'syllabus', fileId: null, version: null, name: 'Fictional', sections: [], chars: 0, ocr: false }, consent: { syllabusOnly: true, at, rememberProfile: false },
        extraction: null, read: null, questions: [], confirmedOutcomes: null, teachingNote: '', options: null, selection: null, plan: null, provisioning: { jobId: 'previous', done: 1, total: 1, error: null },
        created: { outcomeIds: [], moduleIds: [], lessonIds: [], blockIds: [], assignmentIds: [], linkKeys: [] },
        record: { sessionId: 'ds-duplicate-options', source: { name: 'Fictional', kind: 'syllabus', chars: 0 }, extraction: null, read: null, questions: [], confirmedOutcomes: [], optionsShown: [], selection: null, plan: null, appliedAt: null, undoneAt: null, decisions: [] },
      } as DesignSession;
      const job = { id: 'duplicate', courseId: session.courseId, requestedBy: session.createdBy, kind: 'extract', sessionId: session.id, state: 'running', done: 0, total: 1, lessonIds: [], error: null, work: [], instruction: 'options', failures: [], createdAt: at, updatedAt: at } as Parameters<Repo['putGenerationJob']>[0];
      await repo.putDesignSession(session); await repo.putGenerationJob(job);
      const before = await repo.getDesignSession(session.id);
      expect(await repo.claimDesignOptions({ ...session, stage: 'approaches', provisioning: { ...session.provisioning!, jobId: job.id } }, job, 'read', 'previous')).toBe(false);
      expect(await repo.getDesignSession(session.id)).toEqual(before);
      expect(await repo.saveDesignOptions(session.id, 'previous', { ...session, stage: 'approaches' })).toBe(false);
    });
    it('orders equal-position outcomes and the course mirror by id', async () => {
      const repo = await makeRepo();
      const course = (await repo.getCourse('c-stat110'))!;
      const rows = [{ id: 'o-z', courseId: course.id, code: 'O2', text: 'Second', position: 0, aiState: 'draft' as const }, { id: 'o-a', courseId: course.id, code: 'O1', text: 'First', position: 0, aiState: 'draft' as const }];
      await repo.replaceOutcomes(course.id, rows);
      expect((await repo.listOutcomes(course.id)).map(row => row.id)).toEqual(['o-a', 'o-z']);
      expect(await repo.keepOutcome(course.id, 'o-z', 'Second', 'Fictional reviewer', '2026-09-28T12:00:00.000Z')).toBe(true);
      expect(await repo.keepOutcome(course.id, 'o-a', 'First', 'Fictional reviewer', '2026-09-28T12:00:00.000Z')).toBe(true);
      expect((await repo.getCourse(course.id))?.outcomes).toEqual(['First', 'Second']);
    });
    it('conditionally replaces outcomes only when the saved snapshot is current', async () => {
      const repo = await makeRepo(), courseId = 'c-stat110';
      const original = await repo.listOutcomes(courseId);
      const changed = original.map((item, index) => index ? item : { ...item, text: 'Fictional revision' });
      expect(await repo.replaceOutcomesIfUnchanged(courseId, original, changed)).toBe(true);
      expect((await repo.listOutcomes(courseId))[0].text).toBe('Fictional revision');
      expect((await repo.getCourse(courseId))!.outcomes[0]).toBe('Fictional revision');
      expect(await repo.replaceOutcomesIfUnchanged(courseId, original, original)).toBe(false);
      expect(await repo.listOutcomes(courseId)).toEqual(changed);
    });
    it('allows exactly one of two concurrent outcome replacements from one snapshot', async () => {
      const repo = await makeRepo(), courseId = 'c-stat110';
      const original = await repo.listOutcomes(courseId);
      const first = original.map((item, index) => index ? item : { ...item, text: 'First fictional revision' });
      const second = original.map((item, index) => index ? item : { ...item, text: 'Second fictional revision' });
      const result = await Promise.all([repo.replaceOutcomesIfUnchanged(courseId, original, first), repo.replaceOutcomesIfUnchanged(courseId, original, second)]);
      expect(result.filter(Boolean)).toHaveLength(1);
      expect(await repo.listOutcomes(courseId)).toEqual(result[0] ? first : second);
    });
    it('compares course details in the write while preserving the outcomes mirror', async () => {
      const repo = await makeRepo(), original = (await repo.getCourse('c-stat110'))!;
      const [first, second] = await Promise.all([
        repo.updateCourseDetails({ ...original, title: 'First fictional title', outcomes: ['Stale mirror'] }, original),
        repo.updateCourseDetails({ ...original, title: 'Second fictional title', outcomes: ['Stale mirror'] }, original),
      ]);
      expect([first, second].filter(Boolean)).toHaveLength(1);
      expect((await repo.getCourse(original.id))?.title).toBe(first ? 'First fictional title' : 'Second fictional title');
      expect((await repo.getCourse(original.id))?.outcomes).toEqual(original.outcomes);
    });
    it('appends concurrent design decisions without losing either entry', async () => {
      const repo = await makeRepo();
      const at = '2026-09-28T12:00:00Z';
      const session = { id: 'ds-decisions', courseId: 'c-stat110', mode: 'syllabus', stage: 'review', createdBy: 'u-okafor', createdAt: at, updatedAt: at,
        source: { kind: 'syllabus', fileId: null, version: null, name: 'Fictional', sections: [], chars: 0, ocr: false }, consent: { syllabusOnly: true, at, rememberProfile: false },
        extraction: null, read: null, questions: [], confirmedOutcomes: null, teachingNote: '', options: null, selection: null, plan: null, provisioning: null,
        created: { outcomeIds: [], moduleIds: [], lessonIds: [], blockIds: [], assignmentIds: [], linkKeys: [] },
        record: { sessionId: 'ds-decisions', source: { name: 'Fictional', kind: 'syllabus', chars: 0 }, extraction: null, read: null, questions: [], confirmedOutcomes: [], optionsShown: [], selection: null, plan: null, appliedAt: null, undoneAt: null, decisions: [] },
      } as DesignSession;
      await repo.putDesignSession(session);
      expect(await Promise.all(['Kept A', 'Kept B'].map(what => repo.appendDesignDecision(session.id, { at, who: 'u-okafor', what })))).toEqual([true, true]);
      expect((await repo.getDesignSession(session.id))?.record.decisions.map(item => item.what)).toEqual(['Kept A', 'Kept B']);
      await repo.putDesignSession({ ...session, stage: 'provisioning', provisioning: { jobId: 'gj-stop', done: 0, total: 1, error: null } });
      await repo.putGenerationJob({ id: 'gj-stop', courseId: 'c-stat110', requestedBy: 'u-okafor', kind: 'scaffold', sessionId: session.id, state: 'running', done: 0, total: 1, lessonIds: [], error: null, work: [], instruction: '', failures: [], createdAt: at, updatedAt: at });
      expect(await repo.stopDesignJob(session.id, 'gj-stop', 'Policy disabled.')).toBe(true);
      expect((await repo.getGenerationJob('gj-stop'))?.state).toBe('failed');
      expect((await repo.getDesignSession(session.id))?.provisioning?.error).toBe('Policy disabled.');
    });
    it('commits design creations and exact conditional undo under a session revision', async () => {
      const repo = await makeRepo();
      const at = '2026-09-28T12:00:00Z';
      const session = { id: 'ds-cas', courseId: 'c-stat110', mode: 'syllabus', stage: 'preview', createdBy: 'u-okafor', createdAt: at, updatedAt: at,
        source: { kind: 'syllabus', fileId: null, version: null, name: 'Fictional', sections: [], chars: 0, ocr: false }, consent: { syllabusOnly: true, at, rememberProfile: false },
        extraction: null, read: null, questions: [], confirmedOutcomes: null, teachingNote: '', options: null, selection: null, plan: { hash: 'contract-preview', modules: [{ key: 'module-key', position: 90, lessons: [], assignments: [], assignment: null }], outcomes: [] } as unknown as DesignSession['plan'],
        provisioning: null, created: { outcomeIds: [], moduleIds: [], lessonIds: [], blockIds: [], assignmentIds: [], linkKeys: [] },
        record: { sessionId: 'ds-cas', source: { name: 'Fictional', kind: 'syllabus', chars: 0 }, extraction: null, read: null, questions: [], confirmedOutcomes: [], optionsShown: [], selection: null, plan: null, appliedAt: null, undoneAt: null, decisions: [] },
      } as DesignSession;
      await repo.putDesignSession(session);
      const claimed = { ...session, stage: 'provisioning' as const, applyRevision: 'rev-1', planIds: { modules: {}, lessons: {}, assignments: {}, outcomes: {} }, createdBlocks: {}, provisioning: { jobId: 'job-cas', done: 0, total: 1, error: null } };
      expect(await repo.claimDesignApply(claimed)).toBe(true);
      const module = { id: 'm-cas', courseId: 'c-stat110', title: 'Draft', objective: 'Learn', templateKey: null, position: 90 };
      expect(await repo.putDesignModule(session.id, 'wrong', 'module-key', module)).toBe(false);
      expect(await repo.putDesignModule(session.id, 'rev-1', 'module-key', module)).toBe(true);
      const lesson = { id: 'l-cas', courseId: 'c-stat110', moduleId: module.id, title: 'Draft lesson', objective: 'Learn', minutes: 30, position: 0, status: 'draft' as const, publishedAt: null, templateKey: null };
      expect(await repo.putDesignLesson(session.id, 'rev-1', 'lesson-key', lesson)).toBe(true);
      const outcome = { id: 'o-cas', courseId: 'c-stat110', code: 'O99', text: 'A new outcome', position: 99, aiState: 'draft' as const };
      expect(await repo.appendDesignOutcome(session.id, 'rev-1', outcome)).toBe(true);
      expect((await repo.getDesignSession(session.id))?.planIds?.lessons['lesson-key']).toBe(lesson.id);
      expect((await repo.listOutcomes('c-stat110')).some(o => o.id === outcome.id)).toBe(true);
      expect(await repo.cancelDesignApply(session.id, 'rev-1', 'rev-2')).toBe(true);
      expect(await repo.putDesignModule(session.id, 'rev-1', 'late', { ...module, id: 'm-late' })).toBe(false);
      expect(await repo.deleteDesignLessonIfUnchanged(session.id, 'rev-1', lesson)).toBe(false);
      expect(await repo.deleteDesignLessonIfUnchanged(session.id, 'rev-2', { ...lesson, title: 'Stale title' })).toBe(false);
      expect(await repo.deleteDesignLessonIfUnchanged(session.id, 'rev-2', lesson)).toBe(true);
      expect(await repo.deleteDesignModuleIfUnchanged(session.id, 'rev-2', (await repo.getModule(module.id))!)).toBe(true);
      await repo.setOutcomeLinks('block', 'b-s1-1', [outcome.id]);
      expect(await repo.deleteDesignOutcomeIfUnused(session.id, 'rev-2', outcome.id, outcome.text)).toBe(false);
      await repo.setOutcomeLinks('block', 'b-s1-1', []);
      expect(await repo.deleteDesignOutcomeIfUnused(session.id, 'rev-2', outcome.id, outcome.text)).toBe(true);
    });
    it('stores Night 4 design sessions and instructor profiles with copy isolation, ordering, and reset', async () => {
      const repo = await makeRepo();
      const at = '2026-09-28T12:00:00Z';
      const source = { kind: 'syllabus' as const, fileId: null, version: null, name: 'Fictional syllabus', sections: [{ page: null, heading: '', level: 0, text: 'Sample', lines: ['Sample'] }], chars: 6, ocr: false };
      const record = { sessionId: 'ds-b', source: { name: source.name, kind: source.kind, chars: source.chars }, extraction: null, read: null, questions: [], confirmedOutcomes: [], optionsShown: [], selection: null, plan: null, appliedAt: null, undoneAt: null, decisions: [] };
      const session: DesignSession = { id: 'ds-b', courseId: 'c-stat110', mode: 'syllabus', stage: 'start', createdBy: 'u-okafor', createdAt: at, updatedAt: at, source, consent: { syllabusOnly: true, at, rememberProfile: false }, extraction: null, read: null, questions: [], confirmedOutcomes: null, teachingNote: '', options: null, selection: null, plan: null, provisioning: null, created: { outcomeIds: [], moduleIds: [], lessonIds: [], blockIds: [], assignmentIds: [], linkKeys: [] }, record };
      const profile: InstructorProfile = { userId: 'u-okafor', teachingApproach: 'Practice first', voice: 'Direct', assessmentPreferences: { formativeEveryModule: true, prefers: ['case'] }, disclosureText: 'Drafted from the syllabus and reviewed.', updatedAt: at };
      expect(await repo.getDesignSession(session.id)).toBeNull();
      expect(await repo.getInstructorProfile(profile.userId)).toBeNull();
      await repo.putDesignSession(session);
      session.source.name = 'Mutated';
      expect((await repo.getDesignSession('ds-b'))?.source.name).toBe('Fictional syllabus');
      await repo.putDesignSession({ ...(await repo.getDesignSession('ds-b'))!, stage: 'read', updatedAt: '2026-09-28T13:00:00Z' });
      expect((await repo.getDesignSession('ds-b'))?.stage).toBe('read');
      const preview = { ...(await repo.getDesignSession('ds-b'))!, stage: 'preview' as const, plan: { hash: 'contract-preview', modules: [], outcomes: [] } as unknown as DesignSession['plan'] };
      await repo.putDesignSession(preview);
      const claimed = { ...preview, stage: 'provisioning' as const };
      expect(await Promise.all([repo.claimDesignApply(claimed), repo.claimDesignApply(claimed)])).toEqual([true, false]);
      expect((await repo.getDesignSession('ds-b'))?.stage).toBe('provisioning');
      await repo.putDesignSession({ ...preview, stage: 'read' });
      (await repo.getDesignSession('ds-b'))!.created.moduleIds.push('local');
      expect((await repo.getDesignSession('ds-b'))?.created.moduleIds).toEqual([]);
      const base = (await repo.getDesignSession('ds-b'))!;
      await repo.putDesignSession({ ...base, id: 'ds-a', record: { ...base.record, sessionId: 'ds-a' } });
      await repo.putDesignSession({ ...base, id: 'ds-c', createdAt: '2026-09-29T12:00:00Z', record: { ...base.record, sessionId: 'ds-c' } });
      expect((await repo.listDesignSessions('c-stat110')).map(x => x.id)).toEqual(['ds-c', 'ds-a', 'ds-b']);
      expect(await repo.listDesignSessions('c-comm120')).toEqual([]);
      (await repo.listDesignSessions('c-stat110'))[0].record.decisions.push({ at, who: 'u-okafor', what: 'local' });
      expect((await repo.getDesignSession('ds-c'))?.record.decisions).toEqual([]);
      await repo.putInstructorProfile(profile);
      profile.assessmentPreferences.prefers.push('quiz');
      expect((await repo.getInstructorProfile(profile.userId))?.assessmentPreferences.prefers).toEqual(['case']);
      (await repo.getInstructorProfile(profile.userId))!.voice = 'Changed locally';
      expect((await repo.getInstructorProfile(profile.userId))?.voice).toBe('Direct');
      await repo.putInstructorProfile({ ...profile, voice: 'Warm' });
      expect((await repo.getInstructorProfile(profile.userId))?.voice).toBe('Warm');
      const seeded = seedData(); seeded.designSessions = [base]; seeded.instructorProfiles = [{ ...profile, assessmentPreferences: { formativeEveryModule: true, prefers: ['case'] } }];
      await repo.reset(seeded);
      expect(await repo.getDesignSession('ds-b')).toEqual(base);
      expect(await repo.getInstructorProfile(profile.userId)).toEqual(seeded.instructorProfiles[0]);
      await repo.reset(seedData());
      expect(await repo.listDesignSessions('c-stat110')).toEqual([]);
      expect(await repo.getInstructorProfile(profile.userId)).toBeNull();
    });
    it('persists lesson objectives and generation kinds while omitting null/default fields', async () => {
      const repo = await makeRepo();
      const lesson = (await repo.getLesson('l-stat-1'))!;
      await repo.putLesson({ ...lesson, objective: 'Interpret data.' });
      expect((await repo.getLesson(lesson.id))?.objective).toBe('Interpret data.');
      await repo.putLesson({ ...lesson, objective: null });
      expect(await repo.getLesson(lesson.id)).not.toHaveProperty('objective');
      const at = '2026-09-28T12:00:00Z';
      const job = { id: 'gj-design', courseId: 'c-stat110', requestedBy: 'u-okafor', state: 'running' as const, done: 0, total: 1, lessonIds: [], error: null, work: [], instruction: '', failures: [], createdAt: at, updatedAt: at, kind: 'extract' as const, sessionId: 'ds-b' };
      await repo.putGenerationJob(job);
      expect(await repo.getGenerationJob(job.id)).toEqual(job);
      await repo.putGenerationJob({ ...job, kind: 'generate', sessionId: null });
      const stored = await repo.getGenerationJob(job.id);
      expect(stored).not.toHaveProperty('kind');
      expect(stored).not.toHaveProperty('sessionId');
    });
    it('round trips entities and isolates both reads and writes', async () => {
      const repo = await makeRepo();
      const institution = await repo.getInstitution(); institution.name = 'Changed'; await repo.putInstitution(institution);
      institution.name = 'Changed again'; expect((await repo.getInstitution()).name).toBe('Changed');
      const read = await repo.getInstitution(); read.policy.tutorModes.practice.push('off'); expect((await repo.getInstitution()).policy.tutorModes.practice).toEqual(seedData().institution.policy.tutorModes.practice);
      const user = (await repo.getUser('u-priya'))!; user.name = 'New'; await repo.putUser(user); user.name = 'Mutated'; expect((await repo.getUser('u-priya'))?.name).toBe('New');
      const course = (await repo.getCourse('c-stat110'))!; course.outcomes.push('Extra'); await repo.putCourse(course); course.outcomes.push('Mutated'); expect((await repo.getCourse(course.id))?.outcomes).not.toContain('Mutated');
      const module = (await repo.getModule('m-stat-1'))!; module.title = 'New'; await repo.putModule(module); expect((await repo.getModule(module.id))?.title).toBe('New');
      const lesson = (await repo.getLesson('l-stat-1'))!; lesson.title = 'New'; await repo.putLesson(lesson); expect((await repo.getLesson(lesson.id))?.title).toBe('New');
      const block = (await repo.getBlock('b-s1-1'))!; await repo.putBlock(block); expect(await repo.getBlock(block.id)).toEqual(block);
      const assignment = (await repo.getAssignment('asg-stat-1'))!; assignment.title = 'Edited'; await repo.putAssignment(assignment); assignment.title = 'Changed locally';
      expect((await repo.getAssignment(assignment.id))?.title).toBe('Edited');
      const submission = { id:'sub-contract',assignmentId:assignment.id,studentId:'u-priya',attempt:1,state:'submitted' as const,text:'Answer',fileId:null,link:'',submittedAt:'2026-09-26T00:00:00Z',grade:null };
      await repo.putSubmission(submission); expect(await repo.getSubmission(submission.id)).toEqual(submission);
      const tutorSetting = { activityKind:'lesson' as const, activityId:'l-stat-1', mode:'hints' as const, maxHints:2, allowedSourceIds:['b-s1-1'], setBy:'u-okafor', setAt:'2026-09-26T00:00:00Z' };
      await repo.putTutorSetting(tutorSetting);
      tutorSetting.allowedSourceIds.push('local-change');
      expect((await repo.getTutorSetting('lesson','l-stat-1'))?.allowedSourceIds).toEqual(['b-s1-1']);
      const tutorSession = { id:'ts-contract', studentId:'u-priya', activityKind:'lesson' as const, activityId:'l-stat-1', courseId:'c-stat110', mode:'hints' as const, hintsUsed:0, maxHints:2, answerRequests:0, messages:[], startedAt:'2026-09-26T00:00:00Z', updatedAt:'2026-09-26T00:00:00Z' };
      await repo.putTutorSession(tutorSession);
      expect(await repo.getTutorSession(tutorSession.id)).toEqual(tutorSession);
      expect((await repo.listTutorSessions({ courseId:'c-stat110', studentId:'u-priya', activityKind:'lesson', activityId:'l-stat-1' })).map(s => s.id)).toContain(tutorSession.id);
      const announcement = (await repo.getAnnouncement('a-stat-welcome'))!; await repo.putAnnouncement(announcement); expect(await repo.getAnnouncement(announcement.id)).toEqual(announcement);
      const progress = (await repo.getProgress('u-priya','l-stat-1'))!; await repo.putProgress(progress); expect(await repo.getProgress('u-priya','l-stat-1')).toEqual(progress);
      const session = { id: 'bs-x', courseId: 'c-stat110', prompt: 'x', sources: [], stage: 'brief' as const, brief: null, outline: null, lessonIds: [], provenance: null, createdAt: '2026-09-26T00:00:00Z' };
      await repo.putBuilderSession(session); expect(await repo.getBuilderSession(session.id)).toEqual(session);
      const job = { id: 'gj-contract', courseId: 'c-stat110', requestedBy: 'u-okafor', state: 'running' as const, done: 0, total: 1, lessonIds: [], error: null, work: [{ lessonId: 'l-stat-1', type: 'text' as const }], instruction: 'Keep it short', failures: [], createdAt: '2026-09-26T00:00:00Z', updatedAt: '2026-09-26T00:00:00Z' };
      await repo.putGenerationJob(job); job.work[0].lessonId = 'changed'; expect((await repo.getGenerationJob(job.id))?.work[0].lessonId).toBe('l-stat-1');
      const adaptation = { id: 'ad-contract', studentId: 'u-priya', kind: 'session-length' as const, why: 'Shorter sessions fit.', before: undefined, after: 15, appliedAt: '2026-09-26T00:00:00Z', undoneAt: null };
      await repo.putAdaptation(adaptation);
      expect(await repo.getAdaptation(adaptation.id)).toEqual(adaptation);
      const storedAdaptation = (await repo.getAdaptation(adaptation.id))!;
      storedAdaptation.why = 'Changed locally';
      expect((await repo.getAdaptation(adaptation.id))?.why).toBe(adaptation.why);
      await repo.putAdaptation({ ...adaptation, undoneAt: '2026-09-26T01:00:00Z' });
      expect((await repo.getAdaptation(adaptation.id))?.undoneAt).toBe('2026-09-26T01:00:00Z');
      const updatedUser = (await repo.getUser('u-priya'))!;
      updatedUser.profile = { ...seedData().users.find(u => u.id === 'u-marcus')!.profile!, sessionMinutes: 15 };
      const bundled = { ...adaptation, id: 'ad-bundled' };
      await repo.putUserWithAdaptations(updatedUser, [bundled]);
      expect((await repo.getUser('u-priya'))?.profile?.sessionMinutes).toBe(15);
      expect(await repo.getAdaptation(bundled.id)).toEqual(bundled);
      const storedJob = (await repo.getGenerationJob(job.id))!; storedJob.failures.push({ lessonId: 'l-stat-1', type: 'text', message: 'Failed' }); expect((await repo.getGenerationJob(job.id))?.failures).toEqual([]);
    });
    it('orders users, courses, modules, lessons, blocks, announcements, and sessions', async () => {
      const repo = await makeRepo();
      expect((await repo.listUsers()).map(x => x.role)).toEqual(['administrator','instructor','instructor','student','student','student','student','student','student']);
      expect((await repo.listUsers({ role: 'student' })).map(x => x.name)).toEqual(['Dana Whitfield','Jordan Lee','Marcus Bell','Priya Natarajan','Sam Ortiz','Sofia Alvarez']);
      expect((await repo.listCourses()).map(x => x.code)).toEqual(['COMM 120','OPS 101','STAT 110']);
      expect((await repo.listModules('c-stat110')).map(x => x.id)).toEqual(['m-stat-1','m-stat-2']);
      expect((await repo.listLessons({ courseId: 'c-stat110' })).map(x => x.id)).toEqual(['l-stat-1','l-stat-2','l-stat-3']);
      expect((await repo.listBlocks('l-stat-1')).map(x => x.position)).toEqual([0,1,2,3,4]);
      const seedAssignment = (await repo.getAssignment('asg-stat-1'))!;
      await repo.putAssignment({ ...seedAssignment,id:'asg-later',position:2 });
      await repo.putAssignment({ ...seedAssignment,id:'asg-middle',position:1 });
      expect((await repo.listAssignments({moduleId:'m-stat-1'})).map(x=>x.id)).toEqual(['asg-stat-1','asg-middle','asg-later']);
      const baseSubmission = {id:'sub-one',assignmentId:'asg-stat-1',studentId:'u-priya',attempt:1,state:'submitted' as const,text:'One',fileId:null,link:'',submittedAt:'2026-09-26T00:00:00Z',grade:null};
      await repo.putSubmission(baseSubmission); await repo.putSubmission({...baseSubmission,id:'sub-two',attempt:2,text:'Two'});
      expect((await repo.listSubmissions({assignmentId:'asg-stat-1',studentId:'u-priya'})).map(x=>x.id)).toEqual(['sub-two','sub-one']);
      const a = { id: 'ad-old', studentId: 'u-priya', kind: 'reminders' as const, why: 'Old change.', before: 'off', after: 'daily', appliedAt: '2026-01-01T00:00:00Z', undoneAt: null };
      await repo.putAdaptation(a);
      await repo.putAdaptation({ ...a, id: 'ad-new', appliedAt: '2026-02-01T00:00:00Z' });
      await repo.putAdaptation({ ...a, id: 'ad-other', studentId: 'u-marcus' });
      expect((await repo.listAdaptations('u-priya')).map(x => x.id)).toEqual(['ad-new', 'ad-old']);
      expect((await repo.listAnnouncements({})).map(x => x.id)).toEqual(['a-stat-draft','a-stat-office','a-comm-reading','a-stat-welcome']);
      const base = { courseId: 'c-stat110', prompt: '', sources: [], stage: 'brief' as const, brief: null, outline: null, lessonIds: [], provenance: null };
      await repo.putBuilderSession({ ...base, id: 'bs-old', createdAt: '2026-01-01T00:00:00Z' });
      await repo.putBuilderSession({ ...base, id: 'bs-new', createdAt: '2026-02-01T00:00:00Z' });
      expect((await repo.listBuilderSessions('c-stat110')).map(x => x.id)).toEqual(['bs-new','bs-old']);
    });
    it('replaces blocks, cascades lesson deletion, and keeps first read timestamp', async () => {
      const repo = await makeRepo(); const block = (await repo.getBlock('b-s1-1'))!;
      await repo.replaceBlocks('l-stat-1', [{ ...block, position: 7 }]);
      expect((await repo.listBlocks('l-stat-1')).map(x => x.position)).toEqual([7]);
      expect(await repo.getBlock('b-s1-2')).toBeNull();
      const first = { userId: 'u-priya', announcementId: 'a-stat-office', readAt: '2026-01-01T00:00:00Z' };
      await repo.putRead(first); await repo.putRead({ ...first, readAt: '2026-02-01T00:00:00Z' });
      expect(await repo.listReads({ userId: first.userId, announcementId: first.announcementId })).toEqual([first]);
      await repo.deleteLesson('l-stat-1');
      expect(await repo.getLesson('l-stat-1')).toBeNull(); expect(await repo.getBlock('b-s1-1')).toBeNull(); expect(await repo.getProgress('u-priya','l-stat-1')).toBeNull();
    });
    it('replaces enrollments and resets from an empty seed', async () => {
      const repo = await makeRepo(); await repo.setEnrollments('c-stat110',['u-priya']);
      expect((await repo.listEnrollments({ courseId: 'c-stat110' })).map(x => x.userId)).toEqual(['u-priya']);
      await repo.addEnrollment('c-stat110', 'u-dana'); await repo.addEnrollment('c-stat110', 'u-dana');
      expect((await repo.listEnrollments({ courseId: 'c-stat110' })).map(x => x.userId)).toEqual(['u-dana', 'u-priya']);
      const empty = seedData(); empty.users = []; empty.courses = []; empty.enrollments = []; empty.modules = []; empty.lessons = []; empty.blocks = []; empty.assignments = []; empty.submissions = []; empty.announcements = []; empty.reads = []; empty.progress = []; empty.adaptations = []; empty.builderSessions = []; empty.generationJobs = []; empty.files = []; empty.requirements = []; empty.completionEvents = []; empty.testOuts = []; empty.reportingLines = [];
      await repo.reset(empty); expect(await repo.isEmpty()).toBe(true);
      await repo.reset(seedData()); expect(await repo.isEmpty()).toBe(false); expect(await repo.getUser('u-priya')).not.toBeNull();
      expect(await repo.getAssignment('asg-stat-1')).not.toBeNull();
    });
    it('round trips invitations, finds email without case, orders newest first, and accepts once', async () => {
      const repo = await makeRepo();
      const firstUser = { id: 'u-invite-one', name: 'Sam Ibarra', email: 'sam@example.test', role: 'student' as const, initials: 'SI', profile: null };
      const secondUser = { ...firstUser, id: 'u-invite-two', name: 'Tess Ibarra', email: 'tess@example.test' };
      await repo.putUser(firstUser); await repo.putUser(secondUser);
      const first = { userId: firstUser.id, email: firstUser.email, invitedBy: 'u-admin', invitedAt: '2026-01-01T00:00:00Z', accessGranted: false, accessError: 'Unavailable', acceptedAt: null };
      const second = { ...first, userId: secondUser.id, email: secondUser.email, invitedAt: '2026-02-01T00:00:00Z', accessError: null };
      expect(await repo.hasInvitations()).toBe(false);
      await repo.putInvitation(first); await repo.putInvitation(second);
      expect(await repo.hasInvitations()).toBe(true);
      expect(await repo.getInvitation(first.userId)).toEqual(first);
      expect(await repo.getInvitationByEmail('SAM@EXAMPLE.TEST')).toEqual(first);
      expect((await repo.listInvitations()).map(x => x.userId)).toEqual([secondUser.id, firstUser.id]);
      await repo.putInvitation({ ...first, accessGranted: true, accessError: null });
      await repo.acceptInvitation(first.userId, '2026-03-01T00:00:00Z');
      await repo.acceptInvitation(first.userId, '2026-04-01T00:00:00Z');
      await repo.putInvitation({ ...first, accessGranted: true, accessError: null });
      expect(await repo.getInvitation(first.userId)).toEqual({ ...first, accessGranted: true, accessError: null, acceptedAt: '2026-03-01T00:00:00Z' });
    });
    it('round trips seed structure without optional keys and maps new optional fields', async () => {
      const repo = await makeRepo(), seed = seedData();
      expect(await repo.getInstitution()).toEqual(seed.institution);
      for (const c of seed.courses) expect(await repo.getCourse(c.id)).toEqual(c);
      for (const m of seed.modules) expect(await repo.getModule(m.id)).toEqual(m);
      for (const l of seed.lessons) expect(await repo.getLesson(l.id)).toEqual(l);
      for (const b of seed.blocks) expect(await repo.getBlock(b.id)).toEqual(b);
      const institution = { ...seed.institution, templateId: 'tpl-1', readinessPolicy: { rubricId: 'rubric-1', minimumPercent: 80 } };
      await repo.putInstitution(institution); expect(await repo.getInstitution()).toEqual(institution);
      institution.readinessPolicy.minimumPercent = 90; expect((await repo.getInstitution()).readinessPolicy?.minimumPercent).toBe(80);
      const course = { ...seed.courses[0], programId: 'program-1' };
      const module = { ...seed.modules[0], objective: 'Compare questions', templateKey: 'm-1' };
      const lesson = { ...seed.lessons[0], templateKey: 'l-1' };
      const block = { ...seed.blocks[0], templateKey: 'b-1', source: { blockId: 'b-master', hash: 'abc' } };
      await repo.putCourse(course); await repo.putModule(module); await repo.putLesson(lesson); await repo.putBlock(block);
      expect(await repo.getCourse(course.id)).toEqual(course);
      expect(await repo.getModule(module.id)).toEqual(module);
      expect(await repo.getLesson(lesson.id)).toEqual(lesson);
      expect(await repo.getBlock(block.id)).toEqual(block);
      await repo.replaceBlocks(block.lessonId, [block]); expect(await repo.getBlock(block.id)).toEqual(block);
      await repo.putInstitution(seed.institution); await repo.putCourse(seed.courses[0]); await repo.putModule(seed.modules[0]); await repo.putLesson(seed.lessons[0]); await repo.putBlock(seed.blocks[0]);
      expect(await repo.getInstitution()).toEqual(seed.institution);
      expect(await repo.getCourse(course.id)).toEqual(seed.courses[0]);
      expect(await repo.getModule(module.id)).toEqual(seed.modules[0]);
      expect(await repo.getLesson(lesson.id)).toEqual(seed.lessons[0]);
      expect(await repo.getBlock(block.id)).toEqual(seed.blocks[0]);
    });
    it('omits Night 3 optional fields written as null, in both repos', async () => {
      const repo = await makeRepo();
      const module = (await repo.getModule('m-stat-1'))!;
      await repo.putModule({ ...module, objective: null, templateKey: null });
      expect(await repo.getModule(module.id)).toEqual(module);
      const lesson = (await repo.getLesson('l-stat-1'))!;
      await repo.putLesson({ ...lesson, templateKey: null, variantOf: null });
      expect(await repo.getLesson(lesson.id)).toEqual(lesson);
      const block = (await repo.getBlock('b-s1-1'))!;
      await repo.putBlock({ ...block, templateKey: null, source: null });
      expect(await repo.getBlock(block.id)).toEqual(block);
      const course = (await repo.getCourse('c-stat110'))!;
      await repo.putCourse({ ...course, programId: null });
      expect(await repo.getCourse(course.id)).toEqual(course);
      const withSync = { ...lesson, id: 'l-sync', variantOf: { lessonId: lesson.id, audience: 'plain' as const, syncedAt: '2026-09-27T01:02:03.000Z' } };
      await repo.putLesson(withSync);
      expect(await repo.getLesson('l-sync')).toEqual(withSync);
    });
    it('keeps variants out of outlines and deletes their blocks and progress with the master', async () => {
      const repo = await makeRepo(); const master = (await repo.getLesson('l-stat-1'))!;
      const plain = { ...master, id: 'l-plain', variantOf: { lessonId: master.id, audience: 'plain' as const, syncedAt: '2026-09-27T00:00:00.000Z' } };
      const micro = { ...master, id: 'l-micro', variantOf: { lessonId: master.id, audience: 'micro' as const, syncedAt: '2026-09-27T00:00:00.000Z' } };
      await repo.putLesson(plain); await repo.putLesson(micro);
      await expect(repo.putLesson({ ...micro, id: 'l-micro-duplicate' })).rejects.toThrow();
      expect((await repo.listLessons({ courseId: master.courseId })).map(x => x.id)).not.toContain(plain.id);
      expect((await repo.listLessons({ moduleId: master.moduleId })).map(x => x.id)).not.toContain(micro.id);
      expect(await repo.listVariantLessons(master.id)).toEqual([micro, plain]);
      const block = { ...(await repo.getBlock('b-s1-1'))!, id: 'b-variant', lessonId: micro.id };
      await repo.putBlock(block);
      await repo.putProgress({ userId: 'u-priya', lessonId: micro.id, state: 'completed', checks: {}, updatedAt: '2026-09-27T00:00:00Z' });
      await repo.deleteLesson(master.id);
      expect(await repo.getLesson(plain.id)).toBeNull(); expect(await repo.getLesson(micro.id)).toBeNull();
      expect(await repo.getBlock(block.id)).toBeNull(); expect(await repo.getProgress('u-priya', micro.id)).toBeNull();
    });
    it('stores programs, templates, custom rubrics, and readiness items with copy isolation', async () => {
      const repo = await makeRepo(); const at = '2026-09-27T00:00:00Z';
      const program: Program = { id: 'p-z', name: 'Zeta', description: 'Training', templateId: null, brand: { accent: 'teal', logo: null }, createdAt: at };
      await repo.putProgram(program); await repo.putProgram({ ...program, id: 'p-a', name: 'Alpha' });
      expect((await repo.listPrograms()).map(x => x.id)).toEqual(['p-a', 'p-z']);
      expect(await repo.getProgram(program.id)).toEqual(program);
      (await repo.getProgram(program.id))!.brand.accent = 'blue'; expect((await repo.getProgram(program.id))?.brand.accent).toBe('teal');
      await repo.putProgram({ ...program, description: 'Updated' }); expect((await repo.getProgram(program.id))?.description).toBe('Updated');
      await repo.deleteProgram('p-a'); expect(await repo.getProgram('p-a')).toBeNull();
      const template: CourseTemplate = { id: 't-z', name: 'Zeta', description: '', owner: { kind: 'program', programId: program.id }, modules: [{ key: 'm', title: 'Start', placement: 'start', objective: 'Learn', lessons: [] }], tutorDefaults: { lesson: 'hints', assignment: 'off' }, accessFloor: 80, updatedBy: 'u-admin', updatedAt: at };
      await repo.putTemplate(template); await repo.putTemplate({ ...template, id: 't-a', name: 'Alpha', owner: { kind: 'institution' } });
      expect((await repo.listTemplates()).map(x => x.id)).toEqual(['t-a', 't-z']); expect(await repo.getTemplate(template.id)).toEqual(template);
      (await repo.getTemplate(template.id))!.modules[0].title = 'Changed'; expect((await repo.getTemplate(template.id))?.modules[0].title).toBe('Start');
      await repo.deleteTemplate('t-a'); expect(await repo.getTemplate('t-a')).toBeNull();
      const rubric: Rubric = { id: 'r-z', name: 'Zeta', source: 'custom', builtIn: false, version: '1', attribution: null, standards: [{ id: 's', number: '1', title: 'Standard', description: '', items: [] }], updatedAt: at };
      await repo.putRubric(rubric); await repo.putRubric({ ...rubric, id: 'r-a', name: 'Alpha' });
      expect((await repo.listRubrics()).map(x => x.id)).toEqual(['r-a', 'r-z']); expect(await repo.getRubric(rubric.id)).toEqual(rubric);
      await repo.putRubric({ ...rubric, source: 'tessera', builtIn: true }); expect(await repo.getRubric(rubric.id)).toEqual(rubric);
      (await repo.getRubric(rubric.id))!.standards[0].title = 'Changed'; expect((await repo.getRubric(rubric.id))?.standards[0].title).toBe('Standard');
      await repo.deleteRubric('r-a'); expect(await repo.getRubric('r-a')).toBeNull();
      const item: StoredReadinessItem = { courseId: 'c-stat110', rubricId: rubric.id, itemId: 'i-b', finding: null, attestation: { status: 'attested', by: 'u-admin', byName: 'Alex', note: 'Checked', at }, updatedAt: at };
      await repo.putReadinessItem(item); await repo.putReadinessItem({ ...item, itemId: 'i-a' });
      expect((await repo.listReadinessItems(item.courseId, item.rubricId)).map(x => x.itemId)).toEqual(['i-a', 'i-b']);
      (await repo.listReadinessItems(item.courseId, item.rubricId))[0].attestation!.note = 'Changed';
      expect((await repo.listReadinessItems(item.courseId, item.rubricId))[0].attestation!.note).toBe('Checked');
      await repo.putReadinessItem({ ...item, finding: null, attestation: null }); expect((await repo.listReadinessItems(item.courseId, item.rubricId)).map(x => x.itemId)).toEqual(['i-a']);
    });
    it('derives seed outcomes and replaces outcomes and links by course and target', async () => {
      const repo = await makeRepo(); const seed = seedData();
      for (const course of seed.courses) expect(await repo.listOutcomes(course.id)).toEqual(course.outcomes.map((text, i) => ({ id: `${course.id}-o${i + 1}`, courseId: course.id, code: `O${i + 1}`, text, position: i })));
      const original = await repo.listOutcomes('c-stat110');
      original[0].text = 'Changed locally'; expect((await repo.listOutcomes('c-stat110'))[0].text).not.toBe('Changed locally');
      original[0] = (await repo.listOutcomes('c-stat110'))[0];
      await repo.setOutcomeLinks('block', 'b-s1-4', [original[0].id, original[1].id]);
      await repo.setOutcomeLinks('assignment', 'asg-stat-1', [original[1].id]);
      expect((await repo.listOutcomeLinks({ courseId: 'c-stat110' })).map(x => x.outcomeId)).toEqual([original[0].id, original[1].id, original[1].id]);
      expect((await repo.listOutcomeLinks({ targetKind: 'block', targetId: 'b-s1-4' })).map(x => x.outcomeId)).toEqual([original[0].id, original[1].id]);
      await repo.replaceOutcomes('c-stat110', [original[0], { ...original[2], position: 1 }]);
      expect((await repo.listOutcomes('c-stat110')).map(x => x.id)).toEqual([original[0].id, original[2].id]);
      expect((await repo.listOutcomeLinks({ courseId: 'c-stat110' })).map(x => x.outcomeId)).toEqual([original[0].id]);
      await repo.setOutcomeLinks('block', 'b-s1-4', []); expect(await repo.listOutcomeLinks({ targetId: 'b-s1-4' })).toEqual([]);
      const blank = seedData(); blank.courses[0].outcomes = ['One', ' ', 'Three']; await repo.reset(blank);
      expect((await repo.listOutcomes('c-stat110')).map(x => [x.id, x.code, x.position])).toEqual([['c-stat110-o1', 'O1', 0], ['c-stat110-o3', 'O3', 2]]);
    });
    it('filters requirements and keeps completion events append-only and chronological', async () => {
      const repo = await makeRepo(); const at = '2026-09-27T00:00:00Z';
      const r: Requirement = { id: 'req-1', target: { kind: 'course', courseId: 'c-stat110' }, audience: { kind: 'users', userIds: ['u-priya'] }, dueAt: null, recurrence: 'annual', createdBy: 'u-admin', createdAt: at };
      await repo.putRequirement(r); await repo.putRequirement({ ...r, id: 'req-2', target: { kind: 'program', programId: 'p-1' }, createdAt: '2026-09-28T00:00:00Z' });
      expect(await repo.getRequirement(r.id)).toEqual(r);
      expect((await repo.listRequirements()).map(x => x.id)).toEqual(['req-2', 'req-1', 'req-ops-dana']);
      expect((await repo.listRequirements({ targetKind: 'course', targetId: 'c-stat110' })).map(x => x.id)).toEqual([r.id]);
      (await repo.getRequirement(r.id))!.audience = { kind: 'role', role: 'student' }; expect(await repo.getRequirement(r.id)).toEqual(r);
      await repo.putRequirement({ ...r, dueAt: '2026-10-01T00:00:00Z' }); expect((await repo.getRequirement(r.id))?.dueAt).toBe('2026-10-01T00:00:00Z');
      await repo.deleteRequirement(r.id); expect(await repo.getRequirement(r.id)).toBeNull();
      const e = { id: 'e-b', at, userId: 'u-priya', courseId: 'c-stat110', requirementId: r.id, kind: 'assigned' as const, actorId: 'u-admin', detail: 'Assigned.' };
      await repo.appendCompletionEvent(e); await repo.appendCompletionEvent({ ...e, id: 'e-a' });
      expect((await repo.listCompletionEvents({ userId: e.userId, courseId: e.courseId, since: at })).map(x => x.id)).toEqual(['e-a', 'e-b']);
      await expect(repo.appendCompletionEvent(e)).rejects.toThrow();
      expect((await repo.listCompletionEvents({ since: '2026-09-28T00:00:00Z' }))).toEqual([]);
    });
    it('stores test-outs and attempts and enforces certificate uniqueness and replacement', async () => {
      const repo = await makeRepo(); const at = '2026-09-27T00:00:00Z';
      const t = { courseId: 'c-stat110', items: [{ id: 'q', question: 'Which?', options: [{ id: 'a', text: 'A' }], correctOptionId: 'a' }], passPercent: 80, updatedBy: 'u-admin', updatedAt: at };
      await repo.putTestOut(t); expect(await repo.getTestOut(t.courseId)).toEqual(t);
      await expect(repo.putTestOut({ ...t, passPercent: 0 })).rejects.toThrow();
      (await repo.getTestOut(t.courseId))!.items[0].question = 'Changed'; expect((await repo.getTestOut(t.courseId))?.items[0].question).toBe('Which?');
      await repo.putTestOut({ ...t, passPercent: 90 }); expect((await repo.getTestOut(t.courseId))?.passPercent).toBe(90);
      const attempt = { id: 'a-2', courseId: t.courseId, userId: 'u-priya', percent: 85, passed: true, at };
      await repo.putTestOutAttempt(attempt); await repo.putTestOutAttempt({ ...attempt, id: 'a-1' });
      expect((await repo.listTestOutAttempts('u-priya', t.courseId)).map(x => x.id)).toEqual(['a-1', 'a-2']);
      expect((await repo.listTestOutAttempts('u-priya', t.courseId))[0].passed).toBe(true);
      await repo.deleteTestOut(t.courseId); expect(await repo.getTestOut(t.courseId)).toBeNull();
      const cert: Certificate = { id: 'cert-1', code: 'CODE-1', userId: 'u-priya', learnerName: 'Priya', courseId: t.courseId, courseTitle: 'Statistics', issuedAt: at, basis: 'completed', replaces: null, replacedBy: null };
      await repo.insertCertificate(cert); expect(await repo.getCertificate(cert.id)).toEqual(cert); expect(await repo.getCertificateByCode(cert.code)).toEqual(cert);
      await expect(repo.insertCertificate({ ...cert, id: 'cert-2' })).rejects.toThrow();
      await expect(repo.insertCertificate({ ...cert, code: 'CODE-2' })).rejects.toThrow();
      await repo.insertCertificate({ ...cert, id: 'cert-3', code: 'CODE-3', issuedAt: '2026-09-28T00:00:00Z' });
      expect((await repo.listCertificates({ userId: 'u-priya', courseId: t.courseId })).map(x => x.id)).toEqual(['cert-3', 'cert-1']);
      await repo.markCertificateReplaced(cert.id, 'cert-3'); expect((await repo.getCertificate(cert.id))?.replacedBy).toBe('cert-3');
      await expect(repo.markCertificateReplaced(cert.id, 'cert-3')).rejects.toMatchObject({ code: 'conflict' });
      await expect(repo.markCertificateReplaced('missing', 'cert-3')).rejects.toMatchObject({ code: 'conflict' });
    });
    it('keeps the first reporting timestamp and clears consent on removal and reset', async () => {
      const repo = await makeRepo(); const line = { managerId: 'u-admin', reportId: 'u-priya', createdBy: 'u-admin', createdAt: '2026-09-27T00:00:00Z' };
      await repo.putReportingLine(line); await repo.putReportingLine({ ...line, createdAt: '2026-09-28T00:00:00Z' });
      await expect(repo.putReportingLine({ ...line, reportId: line.managerId })).rejects.toThrow();
      expect(await repo.listReportingLines({ managerId: line.managerId, reportId: line.reportId })).toEqual([line]);
      await repo.putManagerConsent({ managerId: line.managerId, reportId: line.reportId, sharing: true, at: line.createdAt });
      expect(await repo.listManagerConsents({ reportId: line.reportId })).toEqual([{ managerId: line.managerId, reportId: line.reportId, sharing: true, at: line.createdAt }]);
      await repo.putManagerConsent({ managerId: line.managerId, reportId: line.reportId, sharing: false, at: line.createdAt });
      expect((await repo.listManagerConsents({ managerId: line.managerId }))[0].sharing).toBe(false);
      await repo.deleteReportingLine(line.managerId, line.reportId);
      expect(await repo.listReportingLines({ managerId: line.managerId })).toEqual([]); expect(await repo.listManagerConsents({})).toEqual([]);
      await repo.putManagerConsent({ managerId: line.managerId, reportId: line.reportId, sharing: true, at: line.createdAt });
      await repo.deleteReportingLine(line.managerId, line.reportId);
      expect(await repo.listManagerConsents({})).toEqual([]);
      await repo.putReportingLine(line); await repo.putManagerConsent({ managerId: line.managerId, reportId: line.reportId, sharing: true, at: line.createdAt });
      await repo.reset(seedData()); expect(await repo.listReportingLines({})).toEqual(seedData().reportingLines); expect(await repo.listManagerConsents({})).toEqual([]);
    });
    it('loads supplied Night 3 seed arrays and clears them on the next reset', async () => {
      const repo = await makeRepo(), seed = seedData(), at = '2026-09-27T00:00:00Z';
      seed.programs = [{ id: 'p-seed', name: 'Program', description: '', templateId: null, brand: { accent: null, logo: null }, createdAt: at }];
      seed.templates = [{ id: 't-seed', name: 'Template', description: '', owner: { kind: 'institution' }, modules: [], tutorDefaults: { lesson: 'hints', assignment: 'off' }, accessFloor: null, updatedBy: 'u-admin', updatedAt: at }];
      seed.rubrics = [{ id: 'r-seed', name: 'Rubric', source: 'custom', builtIn: false, version: '1', attribution: null, standards: [], updatedAt: at }];
      seed.outcomes = [{ id: 'o-seed', courseId: 'c-stat110', code: 'OS', text: 'Seeded outcome', position: 0 }];
      seed.outcomeLinks = [{ outcomeId: 'o-seed', targetKind: 'block', targetId: 'b-s1-4' }];
      seed.requirements = [{ id: 'req-seed', target: { kind: 'course', courseId: 'c-stat110' }, audience: { kind: 'role', role: 'student' }, dueAt: null, recurrence: 'none', createdBy: 'u-admin', createdAt: at }];
      seed.completionEvents = [{ id: 'e-seed', at, userId: 'u-priya', courseId: 'c-stat110', requirementId: 'req-seed', kind: 'assigned', actorId: 'u-admin', detail: 'Assigned.' }];
      seed.testOuts = [{ courseId: 'c-stat110', items: [], passPercent: 80, updatedBy: 'u-admin', updatedAt: at }];
      seed.testOutAttempts = [{ id: 'a-seed', courseId: 'c-stat110', userId: 'u-priya', percent: 90, passed: true, at }];
      seed.certificates = [{ id: 'c-seed', code: 'SEED', userId: 'u-priya', learnerName: 'Priya', courseId: 'c-stat110', courseTitle: 'Statistics', issuedAt: at, basis: 'completed', replaces: null, replacedBy: null }];
      seed.reportingLines = [{ managerId: 'u-admin', reportId: 'u-priya', createdBy: 'u-admin', createdAt: at }];
      seed.managerConsents = [{ managerId: 'u-admin', reportId: 'u-priya', sharing: true, at }];
      await repo.reset(seed);
      expect(await repo.listPrograms()).toEqual(seed.programs);
      expect(await repo.listTemplates()).toEqual(seed.templates);
      expect(await repo.listRubrics()).toEqual(seed.rubrics);
      expect(await repo.listOutcomes('c-stat110')).toEqual(seed.outcomes);
      expect(await repo.listOutcomes('c-comm120')).toEqual([]);
      expect(await repo.listOutcomeLinks({ courseId: 'c-stat110' })).toEqual(seed.outcomeLinks);
      expect(await repo.listRequirements()).toEqual(seed.requirements);
      expect(await repo.listCompletionEvents({})).toEqual(seed.completionEvents);
      expect(await repo.getTestOut('c-stat110')).toEqual(seed.testOuts[0]);
      expect(await repo.listTestOutAttempts('u-priya', 'c-stat110')).toEqual(seed.testOutAttempts);
      expect(await repo.listCertificates({})).toEqual(seed.certificates);
      expect(await repo.listReportingLines({})).toEqual(seed.reportingLines);
      expect(await repo.listManagerConsents({})).toEqual(seed.managerConsents);
      await repo.reset(seedData());
      expect(await repo.listPrograms()).toEqual([]); expect(await repo.listTemplates()).toEqual([]); expect(await repo.listRubrics()).toEqual([]);
      const fresh = seedData();
      expect(await repo.listOutcomeLinks({})).toEqual([]); expect(await repo.listRequirements()).toEqual(fresh.requirements); expect(await repo.listCompletionEvents({})).toEqual(fresh.completionEvents);
      expect(await repo.getTestOut('c-stat110')).toBeNull(); expect(await repo.listTestOutAttempts('u-priya', 'c-stat110')).toEqual([]);
      expect(await repo.listCertificates({})).toEqual([]); expect(await repo.listReportingLines({})).toEqual(fresh.reportingLines); expect(await repo.listManagerConsents({})).toEqual([]);
    });
  });
}
