// Feasibility check for the syllabus design partner (handoff/SYLLABUS-DESIGN-PARTNER-SPEC.md, §7.1):
// can the existing Tessera Access parsers (pdfjs for PDF, JSZip for DOCX) recover the text a
// syllabus extraction needs (outcomes, grading weights, weekly schedule, contact, credits) with
// page anchors? The fixtures are fictional (Meridian State, Dr. Okafor) and were generated by
// reportlab and python-docx, so they stand in for "a syllabus a department template produces",
// not for every real-world layout. Real syllabi are the evaluation set the spec calls for.
import { describe, it, expect } from 'vitest';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { checkDocument } from './index';

const fixture = async (name: string) => {
  const buf = await readFile(fileURLToPath(new URL(`../../tests/fixtures/syllabus/${name}`, import.meta.url)));
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
};
const textOf = (r: Awaited<ReturnType<typeof checkDocument>>) => r.text.sections.map((s) => s.text).join('\n');

describe('syllabus extraction feasibility (pdfjs + JSZip)', () => {
  it('recovers the syllabus text from a PDF with page anchors', async () => {
    const r = await checkDocument('pdf', await fixture('STAT110_Syllabus_Fall2026.pdf'));
    const text = textOf(r);
    expect(r.document?.hasText).toBe(true);
    expect(r.text.sections.length).toBeGreaterThanOrEqual(5); // one section per page
    expect(r.text.sections.every((s) => typeof s.page === 'number')).toBe(true);
    // Outcomes, weights, schedule rows, contact and credits all survive extraction.
    expect(text).toContain('Critique a statistical claim in the news');
    expect(text).toContain('40%');
    expect(text).toContain('Sampling and study design');
    expect(text).toContain('a.okafor@meridianstate.example');
    expect(text).toContain('3 credits');
    // The outcomes are on a later page than the header, so page anchors can cite them.
    const outcomesPage = r.text.sections.find((s) => s.text.includes('Learning outcomes'))?.page;
    expect(outcomesPage).toBeGreaterThan(1);
  });

  it('recovers the syllabus text from a DOCX with heading structure', async () => {
    const r = await checkDocument('docx', await fixture('STAT110_Syllabus_Fall2026.docx'));
    const text = textOf(r);
    const headings = r.text.sections.filter((s) => s.level > 0).map((s) => s.heading);
    expect(headings).toEqual(expect.arrayContaining(['Learning outcomes', 'Grading', 'Course schedule', 'Course policies']));
    expect(text).toContain('Design a simple study to answer a question');
    expect(text).toContain('Weekly quizzes');
    expect(text).toContain('Dec 4');
  });

  it('flattens tables to text, which is the known limit the spec must handle', async () => {
    // pdfjs and the DOCX parser return table cells as text runs, not rows. The extraction task
    // therefore has to reconstruct the grading and schedule tables from text (the model does this
    // well on simple tables) and validate them with rules (weights sum to 100, week count matches
    // the term). If real syllabi defeat this, Docling in the OCR container is the fallback (§10.3).
    const pdf = await checkDocument('pdf', await fixture('STAT110_Syllabus_Fall2026.pdf'));
    const docx = await checkDocument('docx', await fixture('STAT110_Syllabus_Fall2026.docx'));
    for (const r of [pdf, docx]) {
      const text = textOf(r);
      for (const cell of ['Weekly quizzes', '15%', 'Homework sets', '20%', 'Course project', '40%', 'Participation', '5%']) expect(text).toContain(cell);
    }
  });
});
