import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router';
import type { Assignment, BlockContent, Grade, Provenance, RubricCriterion, Submission } from '../../../../shared/domain';
import { AiContent, Button, DataTable, FormField, Select, StatusNotice, TextArea, TextInput, TopBar } from '../../components';
import { useApiMutation, useApiQuery } from '../../data/hooks';
import { dataMode } from '../../data/client';
import { paths } from '../../paths';
import { renderRouterLink } from '../../shell/RouterLink';
import { ErrorNotice, Loading } from '../../shell/Status';
import { usePageTitle } from '../../shell/usePageTitle';
import styles from './Grading.module.css';

function Field({ label, value, set, type = 'text', error }: { label:string; value:string; set:(v:string)=>void; type?:'text'|'number'|'url'; error?:string }) {
  return <FormField label={label} error={error}>{p => <TextInput {...p} type={type} value={value} onChange={e => set(e.target.value)} />}</FormField>;
}
function Notice({ message, error }: { message:string; error:string }) { return error ? <StatusNotice tone="error" live="assertive">{error}</StatusNotice> : message ? <StatusNotice tone="success" live="polite">{message}</StatusNotice> : null; }
function date(value:string|null) { return value ? new Date(value).toLocaleString() : 'No due date'; }
function localDate(value:string|null) { if (!value) return ''; const d=new Date(value); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`; }
function iso(value:string) { return value ? new Date(value).toISOString() : null; }
function Instructions({ blocks }: { blocks:Assignment['instructions'] }) {
  return blocks.length ? <div>{blocks.map(b => <div key={b.id} className={styles.block}>{b.type === 'heading' ? <h3>{b.text}</h3> : b.type === 'callout' ? <aside className={styles.panel}><strong>{b.title}</strong><p>{b.text}</p></aside> : b.type === 'text' ? <p>{b.text}</p> : null}</div>)}</div> : <p>No instructions yet.</p>;
}

export function GradesPage() {
  const { courseId='' }=useParams(); const navigate=useNavigate(); usePageTitle('Grades');
  const outline=useApiQuery('getCourseOutline',{courseId}); const book=useApiQuery('getGradebook',{courseId}); const list=useApiQuery('listAssignments',{courseId});
  const create=useApiMutation('createAssignment'); const exporting=useApiMutation('exportGradebook');
  const [tab,setTab]=useState<'assignments'|'gradebook'>('assignments'); const [moduleId,setModuleId]=useState(''); const [title,setTitle]=useState(''); const [kind,setKind]=useState<Assignment['submissionType']>('text'); const [points,setPoints]=useState('10'); const [dueAt,setDueAt]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const modules=outline.data?.modules ?? [];
  useEffect(() => { if (!moduleId && modules[0]) setModuleId(modules[0].id); },[moduleId,modules]);
  const run=async (action:()=>Promise<unknown>, success:string)=>{ try { setError(''); await action(); setMessage(success); } catch(e) { setError(e instanceof Error ? e.message : 'Action failed.'); } };
  return <div className={styles.page}><TopBar title="Grades" breadcrumbs={[{label:'My courses',href:paths.teach.courses},{label:outline.data?.course.title ?? 'Course',href:paths.teach.course(courseId)},{label:'Grades'}]} renderLink={renderRouterLink}/>
    {outline.isPending || book.isPending ? <Loading/> : outline.error ? <ErrorNotice error={outline.error} onRetry={()=>void outline.refetch()}/> : book.error ? <ErrorNotice error={book.error} onRetry={()=>void book.refetch()}/> : <><Notice message={message} error={error}/><div className={styles.row} role="tablist" aria-label="Grades sections"><Button id="assignments-tab" role="tab" aria-controls="assignments-panel" aria-selected={tab==='assignments'} onClick={()=>setTab('assignments')}>Assignments</Button><Button id="gradebook-tab" role="tab" aria-controls="gradebook-panel" aria-selected={tab==='gradebook'} onClick={()=>setTab('gradebook')}>Gradebook</Button></div>
      {tab==='assignments' ? <section id="assignments-panel" role="tabpanel" aria-labelledby="assignments-tab" className={styles.stack}><h2>Assignments</h2>{!list.data?.length ? <p>No assignments yet.</p> : <ul className={styles.list}>{list.data.map(a=><li key={a.id} className={styles.panel}><Link to={paths.teach.assignment(courseId,a.id)}>{a.title}</Link><p>{a.status==='published'?'Published':'Draft'} · {a.points} points · Due {date(a.dueAt)}</p></li>)}</ul>}
        <div className={styles.panel}><h3>Create assignment</h3><form className={styles.stack} onSubmit={e=>{e.preventDefault(); void (async()=>{try { const a=await create.mutateAsync({moduleId,title,submissionType:kind,points:Number(points),dueAt:iso(dueAt)}); navigate(paths.teach.assignment(courseId,a.id)); } catch(err) { setError(err instanceof Error ? err.message : 'Could not create assignment.'); }})();}}><FormField label="Module" required>{p=><Select {...p} value={moduleId} onChange={e=>setModuleId(e.target.value)}>{modules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</Select>}</FormField><Field label="Title" value={title} set={setTitle} error={error && !title.trim() ? 'Enter a title.' : undefined}/><FormField label="Submission type">{p=><Select {...p} value={kind} onChange={e=>setKind(e.target.value as Assignment['submissionType'])}><option value="text">Text</option><option value="file">File</option><option value="link">Link</option></Select>}</FormField><Field label="Points" type="number" value={points} set={setPoints}/><FormField label="Due date">{p=><input {...p} type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/>}</FormField><Button type="submit" variant="primary" disabled={create.isPending||!moduleId}>Create</Button></form></div></section>
      : <section id="gradebook-panel" role="tabpanel" aria-labelledby="gradebook-tab" className={styles.stack}><h2>Gradebook</h2><Button onClick={()=>void run(async()=>{const {csv}=await exporting.mutateAsync({courseId}); const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); const a=document.createElement('a'); a.href=url; a.download='gradebook.csv'; a.click(); URL.revokeObjectURL(url);},'CSV downloaded.')}>Download CSV</Button><DataTable caption="Course gradebook" density="compact" rows={book.data?.rows ?? []} rowKey={r=>r.student.id} columns={[{key:'student',header:'Student',render:r=>r.student.name},...(book.data?.assignments ?? []).map(a=>({key:a.id,header:`${a.title} (${a.points})`,render:(r:NonNullable<typeof book.data>['rows'][number])=>{const c=r.cells.find(x=>x.assignmentId===a.id); return c?.released ? String(c.score) : c?.state ?? 'Missing';}})),{key:'total',header:'Total',render:r=>`${r.total} / ${r.possible}`}]}/></section>}</>}
  </div>;
}

export function AssignmentEditor() {
  const {courseId='',assignmentId=''}=useParams(); usePageTitle('Assignment editor');
  const q=useApiQuery('getAssignment',{assignmentId}); const submissions=useApiQuery('listSubmissions',{assignmentId,limit:100});
  const update=useApiMutation('updateAssignment'); const publish=useApiMutation('publishAssignment'); const remove=useApiMutation('deleteAssignment'); const release=useApiMutation('releaseGrades'); const navigate=useNavigate();
  const [title,setTitle]=useState(''); const [dueAt,setDueAt]=useState(''); const [points,setPoints]=useState(''); const [kind,setKind]=useState<Assignment['submissionType']>('text'); const [rubric,setRubric]=useState<RubricCriterion[]>([]); const [blocks,setBlocks]=useState<BlockContent[]>([]); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [selected,setSelected]=useState<string|null>(null);
  const lastSelected=useRef<string|null>(null);
  useEffect(()=>{if(selected){lastSelected.current=selected;requestAnimationFrame(()=>document.getElementById('grading-panel')?.focus());}else if(lastSelected.current){const id=lastSelected.current;requestAnimationFrame(()=>document.getElementById(`grade-${id}`)?.focus());lastSelected.current=null;}},[selected]);
  useEffect(()=>{if(q.data){setTitle(q.data.title);setDueAt(localDate(q.data.dueAt));setPoints(String(q.data.points));setKind(q.data.submissionType);setRubric(q.data.rubric);setBlocks(q.data.instructions.map(b=>b.type==='heading'?{type:'heading',level:b.level,text:b.text}:b.type==='callout'?{type:'callout',tone:b.tone,title:b.title,text:b.text}:b.type==='text'?{type:'text',text:b.text}:{type:'text',text:''}));}},[q.data?.id]);
  const run=async (fn:()=>Promise<unknown>,success:string)=>{try{setError('');await fn();setMessage(success);}catch(e){setError(e instanceof Error?e.message:'Action failed.');}};
  const addCriterion=()=>setRubric([...rubric,{id:crypto.randomUUID(),title:'',description:'',levels:[{id:crypto.randomUUID(),title:'Meets expectations',points:0,description:''}]}]);
  const changeCriterion=(i:number,patch:Partial<RubricCriterion>)=>setRubric(rubric.map((c,j)=>j===i?{...c,...patch}:c));
  const student=submissions.data?.items.find(x=>x.id===selected);
  return <div className={styles.page}><TopBar title={q.data?.title ?? 'Assignment'} breadcrumbs={[{label:'Grades',href:paths.teach.gradebook(courseId)},{label:q.data?.title ?? 'Assignment'}]} renderLink={renderRouterLink}/>{q.isPending?<Loading/>:q.error?<ErrorNotice error={q.error} onRetry={()=>void q.refetch()}/>:q.data&&<><Notice message={message} error={error}/><div className={styles.row}><span>{q.data.status==='published'?'Published':'Draft'}</span><Button onClick={()=>void run(()=>publish.mutateAsync({assignmentId}),'Assignment published.')}>Publish</Button><Button onClick={()=>{if(window.confirm(`Delete “${q.data.title}” and its submissions?`)) void run(async()=>{await remove.mutateAsync({assignmentId});navigate(paths.teach.gradebook(courseId));},'Assignment deleted.');}}>Delete</Button></div>
    <section className={styles.stack}><h2>Assignment details</h2><Field label="Title" value={title} set={setTitle}/><FormField label="Due date">{p=><input {...p} type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/>}</FormField><Field label="Points" type="number" value={points} set={setPoints}/><FormField label="Submission type">{p=><Select {...p} value={kind} onChange={e=>setKind(e.target.value as Assignment['submissionType'])}><option value="text">Text</option><option value="file">File</option><option value="link">Link</option></Select>}</FormField></section>
    <section className={styles.stack}><h2>Rubric</h2>{rubric.map((c,i)=><div key={c.id} className={styles.panel}><Field label={`Criterion ${i+1}`} value={c.title} set={v=>changeCriterion(i,{title:v})}/><Field label="Description" value={c.description} set={v=>changeCriterion(i,{description:v})}/>{c.levels.map((l,j)=><div key={l.id} className={styles.row}><Field label={`Level ${j+1}`} value={l.title} set={v=>changeCriterion(i,{levels:c.levels.map((x,k)=>k===j?{...x,title:v}:x)})}/><Field label="Level points" type="number" value={String(l.points)} set={v=>changeCriterion(i,{levels:c.levels.map((x,k)=>k===j?{...x,points:Number(v)}:x)})}/><Button onClick={()=>changeCriterion(i,{levels:c.levels.filter((_,k)=>k!==j)})}>Remove level</Button></div>)}<Button onClick={()=>changeCriterion(i,{levels:[...c.levels,{id:crypto.randomUUID(),title:'',points:0,description:''}]})}>Add level</Button><Button onClick={()=>setRubric(rubric.filter((_,j)=>i!==j))}>Remove criterion</Button></div>)}<Button onClick={addCriterion}>Add criterion</Button></section>
    <section className={styles.stack}><h2>Instructions</h2>{blocks.map((b,i)=><div key={i} className={styles.panel}><FormField label={`Block ${i+1} type`}>{p=><Select {...p} value={b.type} onChange={e=>{const t=e.target.value;setBlocks(blocks.map((x,j)=>j===i?t==='heading'?{type:'heading',level:2,text:''}:t==='callout'?{type:'callout',tone:'info',title:'',text:''}:{type:'text',text:''}:x));}}><option value="text">Text</option><option value="heading">Heading</option><option value="callout">Callout</option></Select>}</FormField>{b.type==='callout'&&<Field label="Callout title" value={b.title} set={v=>setBlocks(blocks.map((x,j)=>j===i?{...b,title:v}:x))}/>}<FormField label="Content">{p=><TextArea {...p} value={'text' in b?b.text:''} onChange={e=>setBlocks(blocks.map((x,j)=>j===i?{...b,text:e.target.value}:x))}/>}</FormField><Button onClick={()=>setBlocks(blocks.filter((_,j)=>j!==i))}>Remove block</Button></div>)}<Button onClick={()=>setBlocks([...blocks,{type:'text',text:''}])}>Add text block</Button><Button variant="primary" disabled={update.isPending} onClick={()=>void run(()=>update.mutateAsync({assignmentId,title,dueAt:iso(dueAt),points:Number(points),submissionType:kind,rubric,instructions:blocks}),'Assignment saved.')}>Save</Button></section>
    <section className={styles.stack}><h2>Submissions</h2>{submissions.isPending?<Loading/>:submissions.error?<ErrorNotice error={submissions.error} onRetry={()=>void submissions.refetch()}/>:!submissions.data?.items.length?<p>No submissions yet.</p>:<ul>{submissions.data.items.map(s=><li key={s.id}><Button id={`grade-${s.id}`} onClick={()=>setSelected(s.id)}>{s.student.name} · attempt {s.attempt} · {s.state}</Button></li>)}</ul>}<Button onClick={()=>{if(window.confirm('Release all graded submissions for this assignment?')) void run(()=>release.mutateAsync({assignmentId}),'Grades released.');}}>Release grades</Button></section>
    {student&&<GradingView key={student.id} assignment={q.data} submission={student} studentName={student.student.name} onClose={()=>setSelected(null)}/>}
  </>}</div>;
}

function GradingView({assignment,submission,studentName,onClose}:{assignment:Assignment;submission:Submission;studentName:string;onClose:()=>void}) {
  const [criteria,setCriteria]=useState<Grade['criteria']>(submission.grade?.criteria ?? []); const [score,setScore]=useState(String(submission.grade?.score ?? '0')); const [feedback,setFeedback]=useState(submission.grade?.feedback ?? ''); const [origin,setOrigin]=useState<'human'|'ai'>(submission.grade?.feedbackOrigin ?? 'human'); const [provenance,setProvenance]=useState<Provenance|null>(submission.grade?.feedbackProvenance ?? null); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const grade=useApiMutation('gradeSubmission'); const draft=useApiMutation('draftFeedback');
  const setLevel=(c:RubricCriterion,levelId:string)=>{const level=c.levels.find(l=>l.id===levelId); const next=criteria.filter(x=>x.criterionId!==c.id); if(level) next.push({criterionId:c.id,levelId,points:level.points,comment:''}); setCriteria(next); setScore(String(next.reduce((n,x)=>n+x.points,0)));};
  return <section className={styles.stack} id="grading-panel" tabIndex={-1}><div className={styles.row}><h2>Grade {studentName}</h2><Button onClick={onClose}>Close grading</Button></div><Notice message={message} error={error}/><div className={styles.columns}><div className={styles.panel}><h3>Submission</h3><p>Attempt {submission.attempt} · {date(submission.submittedAt)}</p>{submission.text?<p className={styles.block}>{submission.text}</p>:submission.link?<a href={submission.link} target="_blank" rel="noopener noreferrer">Open submitted link</a>:submission.fileId?<a href={/^https?:\/\//.test(submission.fileId)?submission.fileId:`/api/v1/files/${submission.fileId}/content`} target="_blank" rel="noopener noreferrer">Open submitted file</a>:<p>No content.</p>}</div><div className={styles.panel}><h3>Rubric</h3>{assignment.rubric.length?assignment.rubric.map(c=><fieldset key={c.id}><legend>{c.title}</legend><p>{c.description}</p>{c.levels.map(l=><label key={l.id} className={styles.row}><input type="radio" name={`criterion-${c.id}`} checked={criteria.find(x=>x.criterionId===c.id)?.levelId===l.id} onChange={()=>setLevel(c,l.id)}/>{l.title} · {l.points} points</label>)}<Field label="Criterion comment" value={criteria.find(x=>x.criterionId===c.id)?.comment ?? ''} set={v=>setCriteria(criteria.map(x=>x.criterionId===c.id?{...x,comment:v}:x))}/></fieldset>):<p>No rubric attached.</p>}<Field label={`Score out of ${assignment.points}`} type="number" value={score} set={setScore}/><Button disabled={draft.isPending} onClick={()=>void (async()=>{try{const result=await draft.mutateAsync({submissionId:submission.id,criteria});setFeedback(result.feedback);setProvenance(result.provenance);setOrigin('ai');setError('');setMessage('AI draft added. Review and edit before saving.');}catch(e){setError(e instanceof Error?e.message:'Could not draft feedback.');}})()}>Draft feedback with AI</Button>{origin==='ai'&&provenance&&<AiContent kind="note" who="Drafted with AI" source={`from the rubric result · ${provenance.model} · edit before releasing`}><p>{feedback || 'Feedback draft'}</p></AiContent>}<FormField label="Feedback">{p=><TextArea {...p} value={feedback} onChange={e=>setFeedback(e.target.value)}/>}</FormField><Button variant="primary" disabled={grade.isPending} onClick={()=>void (async()=>{try{await grade.mutateAsync({submissionId:submission.id,criteria,score:Number(score),feedback,feedbackOrigin:origin,feedbackProvenance:provenance});setError('');setMessage('Grade saved. Release grades when ready.');}catch(e){setError(e instanceof Error?e.message:'Could not save grade.');}})()}>Save grade</Button></div></div></section>;
}

export function StudentAssignmentPage() {
  const {courseId='',assignmentId=''}=useParams(); usePageTitle('Assignment');
  const q=useApiQuery('getAssignment',{assignmentId}); const mine=useApiQuery('getMySubmission',{assignmentId}); const submit=useApiMutation('submit');
  const [text,setText]=useState(''); const [link,setLink]=useState(''); const [file,setFile]=useState<File|null>(null); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [uploading,setUploading]=useState(false);
  const a=q.data; const s=mine.data; const mockFile=!!a && a.submissionType==='file' && dataMode==='mock';
  const canSubmit=!!a && !mockFile && (!s || (s.attempt<2&&s.state==='submitted')) && (!a.dueAt || new Date(a.dueAt).getTime()>=Date.now());
  const send=async()=>{try{setError('');let fileId: string|undefined;if(a?.submissionType==='file'){if(!file) throw new Error('Choose a file.');setUploading(true);const body=new FormData();body.append('file',file);const response=await fetch(`/api/v1/courses/${courseId}/files/upload`,{method:'POST',body,credentials:'include'});if(!response.ok){const problem=await response.json().catch(()=>null) as {error?:{message?:string}}|null;throw new Error(problem?.error?.message ?? 'File upload failed.');}const record=await response.json() as {id:string};fileId=record.id;}const result=await submit.mutateAsync({assignmentId,text:a?.submissionType==='text'?text:undefined,fileId,link:a?.submissionType==='link'?link:undefined});setMessage(`Attempt ${result.attempt} submitted.`);}catch(e){setError(e instanceof Error?e.message:'Submission failed.');}finally{setUploading(false);}};
  return <div className={styles.page}><TopBar title={a?.title ?? 'Assignment'} breadcrumbs={[{label:'Courses',href:paths.student.courses},{label:'Course',href:paths.student.course(courseId)},{label:a?.title ?? 'Assignment'}]} renderLink={renderRouterLink}/>{q.isPending||mine.isPending?<Loading/>:q.error?<ErrorNotice error={q.error} onRetry={()=>void q.refetch()}/>:mine.error?<ErrorNotice error={mine.error} onRetry={()=>void mine.refetch()}/>:a&&<><Notice message={message} error={error}/><p>{a.points} points · Due {date(a.dueAt)}</p><section><h2>Instructions</h2><Instructions blocks={a.instructions}/></section><section className={styles.stack}><h2>Your submission</h2><p>Status: {s?.state ?? 'Not submitted'}{s?` · Attempt ${s.attempt} of 2`:''}</p>{s?.text&&<p className={styles.block}>{s.text}</p>}{s?.link&&<a href={s.link} target="_blank" rel="noopener noreferrer">Your submitted link</a>}{s?.fileId&&<p>File submitted.</p>}{canSubmit&&<form className={styles.stack} onSubmit={e=>{e.preventDefault();void send();}}>{a.submissionType==='text'&&<FormField label="Your response" required>{p=><TextArea {...p} required value={text} onChange={e=>setText(e.target.value)}/>}</FormField>}{a.submissionType==='link'&&<Field label="Submission link" type="url" value={link} set={setLink}/ >}{a.submissionType==='file'&&<FormField label="Choose a file" required hint="Up to 25 MB.">{p=><input {...p} type="file" onChange={e=>setFile(e.target.files?.[0]??null)}/>}</FormField>}<Button type="submit" variant="primary" disabled={submit.isPending||uploading}>{s?'Resubmit':'Submit'}</Button></form>}{mockFile&&<StatusNotice tone="info">File submissions need the live app; demo mode has no file storage.</StatusNotice>}{!canSubmit&&!mockFile&&<p>{s?.attempt===2?'You have used both attempts.':a.dueAt&&new Date(a.dueAt).getTime()<Date.now()?'The due date has passed.':'This submission cannot be replaced.'}</p>}</section>{s?.grade&&<section className={styles.stack}><h2>Your grade</h2><p>{s.grade.score} / {a.points}</p><h3>Rubric result</h3>{s.grade.criteria.length?<ul>{s.grade.criteria.map(c=>{const criterion=a.rubric.find(x=>x.id===c.criterionId);const level=criterion?.levels.find(x=>x.id===c.levelId);return <li key={c.criterionId}>{criterion?.title}: {level?.title} · {c.points} points{c.comment&&` · ${c.comment}`}</li>;})}</ul>:<p>No rubric result.</p>}<h3>Feedback</h3>{s.grade.feedbackOrigin==='ai'?<AiContent kind="note" who="Drafted with AI" source={`${s.grade.feedbackProvenance?.model ?? 'AI'} · reviewed by your instructor`}><p>{s.grade.feedback}</p></AiContent>:<p>{s.grade.feedback}</p>}</section>}</>}</div>;
}
