import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router';
import type { TemplateInput } from '../../../../shared/api';
import type { BlockContent, CourseTemplate, TemplateBlock, TemplateLesson, TemplateModule, TutorMode } from '../../../../shared/domain';
import { Button, StatusNotice, TopBar } from '../../components';
import { useApiMutation, useApiQuery } from '../../data/hooks';
import { PageHelp } from '../../help/PageHelp';
import { paths } from '../../paths';
import { renderRouterLink } from '../../shell/RouterLink';
import { useSession } from '../../shell/session';
import { ErrorNotice, Loading } from '../../shell/Status';
import { usePageTitle } from '../../shell/usePageTitle';
import styles from './Templates.module.css';
import { uniqueKey } from './keys';

const modes: { value: TutorMode; label: string }[] = [{ value: 'off', label: 'Off' }, { value: 'hints', label: 'Hints' }, { value: 'explain', label: 'Explain' }, { value: 'open', label: 'Open' }];
const blank = (): TemplateInput => ({ name: '', description: '', owner: { kind: 'institution' }, modules: [], tutorDefaults: { lesson: 'hints', assignment: 'hints' }, accessFloor: null });
const fromTemplate = (t: CourseTemplate): TemplateInput => ({ name: t.name, description: t.description, owner: t.owner, modules: structuredClone(t.modules), tutorDefaults: { ...t.tutorDefaults }, accessFloor: t.accessFloor });
function swap<T>(items: T[], index: number, next: number): T[] {
  const copy = [...items]; [copy[index], copy[next]] = [copy[next], copy[index]]; return copy;
}
function starter(kind: 'text' | 'heading' | 'callout', label: string): BlockContent {
  return kind === 'heading' ? { type: 'heading', level: 2, text: label } : kind === 'callout' ? { type: 'callout', tone: 'info', title: label, text: 'Add details here.' } : { type: 'text', text: 'Add details here.' };
}

export function TemplatesPage() {
  usePageTitle('Templates');
  const { institution } = useSession(), navigate = useNavigate();
  const templates = useApiQuery('listTemplates', undefined), programs = useApiQuery('listPrograms', undefined);
  const create = useApiMutation('createTemplate'), setInstitution = useApiMutation('setInstitutionTemplate');
  const [name, setName] = useState(''), [owner, setOwner] = useState('institution'), [error, setError] = useState(''), [message, setMessage] = useState('');
  const usedAt = (id: string) => [institution.templateId === id ? 'Institution' : '', ...(programs.data ?? []).filter(p => p.templateId === id).map(p => p.name)].filter(Boolean).join(', ') || 'Not assigned';
  return <div className={styles.page}><TopBar title="Templates" /><PageHelp topic="admin.templates" />
    <section className={styles.section}><h2>Institution template</h2><label className={styles.field}>Default for courses without a program template<select value={institution.templateId ?? ''} onChange={e => { setError(''); setInstitution.mutate({ templateId: e.target.value || null }, { onSuccess: () => setMessage('Institution template saved.'), onError: x => setError(x.message) }); }} disabled={setInstitution.isPending}><option value="">No institution template</option>{templates.data?.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{message && <StatusNotice tone="success" live="polite">{message}</StatusNotice>}{error && <StatusNotice tone="error">{error}</StatusNotice>}</section>
    <section className={styles.section}><h2>All templates</h2>{templates.isPending || programs.isPending ? <Loading /> : templates.error || programs.error ? <ErrorNotice error={templates.error ?? programs.error} /> : <ul className={styles.list}>{templates.data?.map(t => <li key={t.id}><Link to={paths.admin.template(t.id)}>{t.name}</Link> · {t.owner.kind === 'institution' ? 'Institution owned' : `Program owned: ${programs.data?.find(p => p.id === ('programId' in t.owner ? t.owner.programId : ''))?.name ?? 'Unknown program'}`} · Used by: {usedAt(t.id)}</li>)}{templates.data?.length === 0 && <li>No templates yet.</li>}</ul>}</section>
    <section className={styles.section}><h2>Create template</h2><form className={styles.form} onSubmit={e => { e.preventDefault(); setError(''); create.mutate({ ...blank(), name, owner: owner === 'institution' ? { kind: 'institution' } : { kind: 'program', programId: owner } }, { onSuccess: t => navigate(paths.admin.template(t.id)), onError: x => setError(x.message) }); }}><label className={styles.field}>Name<input required value={name} onChange={e => setName(e.target.value)} /></label><label className={styles.field}>Owner<select value={owner} onChange={e => setOwner(e.target.value)}><option value="institution">Institution</option>{programs.data?.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Button type="submit" variant="primary" disabled={create.isPending}>Create template</Button></form></section>
  </div>;
}

export function TemplatePage() {
  const { templateId = '' } = useParams(), navigate = useNavigate(); usePageTitle('Template editor');
  const templates = useApiQuery('getTemplate', { templateId }, { enabled: !!templateId }), programs = useApiQuery('listPrograms', undefined);
  const update = useApiMutation('updateTemplate'), remove = useApiMutation('deleteTemplate');
  const [draft, setDraft] = useState<TemplateInput | null>(null), [moduleTitle, setModuleTitle] = useState('');
  const [lessonTitles, setLessonTitles] = useState<Record<string, string>>({}), [blockLabels, setBlockLabels] = useState<Record<string, string>>({});
  const [message, setMessage] = useState(''), [error, setError] = useState('');
  useEffect(() => { if (templates.data) setDraft(fromTemplate(templates.data)); }, [templates.data?.id, templates.data?.updatedAt]);
  const change = (fn: (current: TemplateInput) => TemplateInput) => setDraft(current => current ? fn(current) : current);
  const moduleChange = (index: number, fn: (m: TemplateModule) => TemplateModule) => change(d => ({ ...d, modules: d.modules.map((m, i) => i === index ? fn(m) : m) }));
  const lessonChange = (mi: number, li: number, fn: (l: TemplateLesson) => TemplateLesson) => moduleChange(mi, m => ({ ...m, lessons: m.lessons.map((l, i) => i === li ? fn(l) : l) }));
  const blockChange = (mi: number, li: number, bi: number, fn: (b: TemplateBlock) => TemplateBlock) => lessonChange(mi, li, l => ({ ...l, blocks: l.blocks.map((b, i) => i === bi ? fn(b) : b) }));
  const save = (e: FormEvent) => { e.preventDefault(); if (!draft) return; setError(''); setMessage(''); update.mutate({ templateId, ...draft }, { onSuccess: t => { setDraft(fromTemplate(t)); setMessage('Template saved. Existing courses can preview its changes.'); }, onError: x => setError(x.message) }); };
  return <div className={styles.page}><TopBar title={templates.data?.name ?? 'Template editor'} breadcrumbs={[{ label: 'Templates', href: paths.admin.templates }, { label: templates.data?.name ?? 'Template editor' }]} renderLink={renderRouterLink} />
    {templates.error || programs.error ? <ErrorNotice error={templates.error ?? programs.error} /> : templates.isPending || programs.isPending || !draft ? <Loading /> : <form className={styles.form} onSubmit={save}>
      {message && <StatusNotice tone="success" live="polite">{message}</StatusNotice>}{error && <StatusNotice tone="error">{error}</StatusNotice>}
      <section className={styles.section}><h2>Details</h2><label className={styles.field}>Name<input required value={draft.name} onChange={e => change(d => ({ ...d, name: e.target.value }))} /></label><label className={styles.field}>Description<textarea value={draft.description ?? ''} onChange={e => change(d => ({ ...d, description: e.target.value }))} /></label><label className={styles.field}>Owner<select value={draft.owner.kind === 'institution' ? 'institution' : draft.owner.programId} onChange={e => change(d => ({ ...d, owner: e.target.value === 'institution' ? { kind: 'institution' } : { kind: 'program', programId: e.target.value } }))}><option value="institution">Institution</option>{programs.data?.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></section>
      <section className={styles.section}><h2>Required structure</h2><p className={styles.muted}>These items are added to courses. Renaming an item here keeps its identity.</p>
        {draft.modules.map((m, mi) => <div className={styles.editorGroup} key={m.key}><h3>Module {mi + 1}</h3><div className={styles.row}><label className={styles.field}>Title<input required value={m.title} onChange={e => moduleChange(mi, x => ({ ...x, title: e.target.value }))} /></label><label className={styles.field}>Placement<select value={m.placement} onChange={e => moduleChange(mi, x => ({ ...x, placement: e.target.value as 'start' | 'end' }))}><option value="start">Start</option><option value="end">End</option></select></label></div><label className={styles.field}>Objective<textarea value={m.objective} onChange={e => moduleChange(mi, x => ({ ...x, objective: e.target.value }))} /></label><div className={styles.actions}><Button type="button" disabled={mi === 0} onClick={() => change(d => ({ ...d, modules: swap(d.modules, mi, mi - 1) }))}>Move module up</Button><Button type="button" disabled={mi === draft.modules.length - 1} onClick={() => change(d => ({ ...d, modules: swap(d.modules, mi, mi + 1) }))}>Move module down</Button><Button type="button" onClick={() => change(d => ({ ...d, modules: d.modules.filter((_, i) => i !== mi) }))}>Remove module</Button></div>
          {m.lessons.map((l, li) => <div className={styles.editorGroup} key={l.key}><h4>Lesson {li + 1}</h4><div className={styles.row}><label className={styles.field}>Title<input required value={l.title} onChange={e => lessonChange(mi, li, x => ({ ...x, title: e.target.value }))} /></label><label className={styles.field}>Minutes<input type="number" min="1" max="240" required value={l.minutes} onChange={e => lessonChange(mi, li, x => ({ ...x, minutes: Number(e.target.value) }))} /></label></div><div className={styles.actions}><Button type="button" disabled={li === 0} onClick={() => moduleChange(mi, x => ({ ...x, lessons: swap(x.lessons, li, li - 1) }))}>Move lesson up</Button><Button type="button" disabled={li === m.lessons.length - 1} onClick={() => moduleChange(mi, x => ({ ...x, lessons: swap(x.lessons, li, li + 1) }))}>Move lesson down</Button><Button type="button" onClick={() => moduleChange(mi, x => ({ ...x, lessons: x.lessons.filter((_, i) => i !== li) }))}>Remove lesson</Button></div>
            {l.blocks.map((b, bi) => <div className={styles.editorGroup} key={b.key}><h4>Required block {bi + 1}</h4><label className={styles.field}>Label<input required value={b.label} onChange={e => blockChange(mi, li, bi, x => ({ ...x, label: e.target.value }))} /></label><label className={styles.field}>Block type<select value={b.content.type} onChange={e => blockChange(mi, li, bi, x => ({ ...x, content: starter(e.target.value as 'text' | 'heading' | 'callout', x.label) }))}><option value="text">Text</option><option value="heading">Heading</option><option value="callout">Callout</option></select></label>
              {b.content.type === 'heading' && <label className={styles.field}>Heading level<select value={b.content.level} onChange={e => blockChange(mi, li, bi, x => ({ ...x, content: { ...(x.content as Extract<BlockContent, { type: 'heading' }>), level: Number(e.target.value) as 2 | 3 } }))}><option value="2">Level 2</option><option value="3">Level 3</option></select></label>}
              {b.content.type === 'callout' && <><label className={styles.field}>Callout title<input value={b.content.title} onChange={e => blockChange(mi, li, bi, x => ({ ...x, content: { ...(x.content as Extract<BlockContent, { type: 'callout' }>), title: e.target.value } }))} /></label><label className={styles.field}>Callout tone<select value={b.content.tone} onChange={e => blockChange(mi, li, bi, x => ({ ...x, content: { ...(x.content as Extract<BlockContent, { type: 'callout' }>), tone: e.target.value as 'info' | 'tip' | 'warning' } }))}><option value="info">Information</option><option value="tip">Tip</option><option value="warning">Warning</option></select></label></>}
              <label className={styles.field}>{b.content.type === 'heading' ? 'Heading text' : 'Starter text'}<textarea required={b.content.type !== 'callout'} value={'text' in b.content ? b.content.text : ''} onChange={e => blockChange(mi, li, bi, x => ({ ...x, content: { ...x.content, text: e.target.value } as BlockContent }))} /></label><div className={styles.actions}><Button type="button" disabled={bi === 0} onClick={() => lessonChange(mi, li, x => ({ ...x, blocks: swap(x.blocks, bi, bi - 1) }))}>Move block up</Button><Button type="button" disabled={bi === l.blocks.length - 1} onClick={() => lessonChange(mi, li, x => ({ ...x, blocks: swap(x.blocks, bi, bi + 1) }))}>Move block down</Button><Button type="button" onClick={() => lessonChange(mi, li, x => ({ ...x, blocks: x.blocks.filter((_, i) => i !== bi) }))}>Remove block</Button></div></div>)}
            <div className={styles.row}><label className={styles.field}>New required block label<input value={blockLabels[l.key] ?? ''} onChange={e => setBlockLabels(x => ({ ...x, [l.key]: e.target.value }))} /></label><Button type="button" onClick={() => { const label = (blockLabels[l.key] ?? '').trim(); if (!label) return; lessonChange(mi, li, x => ({ ...x, blocks: [...x.blocks, { key: uniqueKey(label, x.blocks.map(b => b.key)), label, content: starter('text', label) }] })); setBlockLabels(x => ({ ...x, [l.key]: '' })); }}>Add block</Button></div>
          </div>)}
          <div className={styles.row}><label className={styles.field}>New lesson title<input value={lessonTitles[m.key] ?? ''} onChange={e => setLessonTitles(x => ({ ...x, [m.key]: e.target.value }))} /></label><Button type="button" onClick={() => { const title = (lessonTitles[m.key] ?? '').trim(); if (!title) return; const used = draft.modules.flatMap(x => x.lessons.map(l => l.key)); moduleChange(mi, x => ({ ...x, lessons: [...x.lessons, { key: uniqueKey(title, used), title, minutes: 15, blocks: [] }] })); setLessonTitles(x => ({ ...x, [m.key]: '' })); }}>Add lesson</Button></div>
        </div>)}
        <div className={styles.row}><label className={styles.field}>New module title<input value={moduleTitle} onChange={e => setModuleTitle(e.target.value)} /></label><Button type="button" onClick={() => { const title = moduleTitle.trim(); if (!title) return; change(d => ({ ...d, modules: [...d.modules, { key: uniqueKey(title, d.modules.map(m => m.key)), title, placement: 'end', objective: '', lessons: [] }] })); setModuleTitle(''); }}>Add module</Button></div>
      </section>
      <section className={styles.section}><h2>Defaults</h2><label className={styles.field}>Lesson tutor mode<select value={draft.tutorDefaults.lesson} onChange={e => change(d => ({ ...d, tutorDefaults: { ...d.tutorDefaults, lesson: e.target.value as TutorMode } }))}>{modes.map(m => <option key={m.value} value={m.value}>{m.label}</option>)}</select></label><label className={styles.field}>Assignment tutor mode<select value={draft.tutorDefaults.assignment} onChange={e => change(d => ({ ...d, tutorDefaults: { ...d.tutorDefaults, assignment: e.target.value as TutorMode } }))}>{modes.map(m => <option key={m.value} value={m.value}>{m.label}</option>)}</select></label><label className={styles.field}>Accessibility floor<input type="number" min="0" max="100" disabled={draft.accessFloor === null} value={draft.accessFloor ?? ''} onChange={e => change(d => ({ ...d, accessFloor: Number(e.target.value) }))} /></label><label><input type="checkbox" checked={draft.accessFloor === null} onChange={e => change(d => ({ ...d, accessFloor: e.target.checked ? null : 0 }))} /> Use the institution's minimum</label></section>
      <div className={styles.actions}><Button type="submit" variant="primary" disabled={update.isPending}>Save template</Button><Button type="button" disabled={remove.isPending} onClick={() => { if (!window.confirm(`Delete template “${templates.data?.name}”?`)) return; setError(''); remove.mutate({ templateId }, { onSuccess: () => navigate(paths.admin.templates), onError: x => setError(x.message) }); }}>Delete template</Button></div>
    </form>}
  </div>;
}
