import type { Id, Timestamp, SubmissionState } from '../domain';

export type CalculationMode = 'weighted' | 'points';
export interface GradeCategory { id: Id; courseId: Id; name: string; position: number; weight: number; drop: { lowest: number; highest: number; keepAtLeast: number }; lateApplies: boolean }
export interface LatePolicy { enabled: boolean; percentPerPeriod: number; period: 'day' | 'hour'; basis: 'score' | 'possible'; maxPeriods: number | null; afterMax: 'missing' | 'hold-at-max'; graceMinutes: number }
export interface MissingPolicy { treatAs: 'zero-after-due' | 'exclude-until-graded'; droppable: boolean }
export interface ExtraCreditPolicy { categoryCapPercent: number | null; courseCapPoints: number | null }
export interface GradeScheme { id: Id; name: string; bands: { letter: string; min: number }[]; rounding: { decimals: 1; mode: 'half-up' }; letterFrom: 'rounded' }
export interface GradebookSetup { courseId: Id; mode: CalculationMode; categories: GradeCategory[]; late: LatePolicy; missing: MissingPolicy; extraCredit: ExtraCreditPolicy; scheme: GradeScheme; emptyCategory: 'share-weight'; studentNotes: { categoryId: Id; text: string }[]; dismissedChecks: { code: SetupCheckCode; target: string; by: Id; at: Timestamp }[]; source: { kind: 'manual' | 'syllabus'; designSessionId: Id | null }; version: number; rulesVersion: number; updatedBy: Id; updatedAt: Timestamp }
export interface StudentItemState { assignmentId: Id; studentId: Id; courseId: Id; excused: { reason: string; studentNote: string | null; by: Id; at: Timestamp } | null; missing: 'force-missing' | 'force-not-missing' | null; lateWaived: { reason: string; by: Id; at: Timestamp } | null; override: { score: number; reason: string; by: Id; at: Timestamp } | null; dueAt: Timestamp | null; version: number }
export interface CourseGradeOverride { courseId: Id; studentId: Id; letter: string | null; percent: number | null; reason: string; by: Id; at: Timestamp; version: number }
export interface CalcItem { assignmentId: Id; title: string; categoryId: Id | null; points: number; extraCredit: boolean; countsTowardGrade: boolean; dueAt: Timestamp | null; extended?: boolean; position: number; submission: { state: SubmissionState; submittedAt: Timestamp; score: number | null; released: boolean } | null; itemState: Pick<StudentItemState, 'excused' | 'missing' | 'lateWaived' | 'override'> | null; hypothetical: number | null }
export interface CalcInput { setup: GradebookSetup; studentId: Id; items: CalcItem[]; view: 'student' | 'held'; now: Timestamp; finalOverride: CourseGradeOverride | null }
export type CellState = 'graded' | 'late' | 'missing' | 'excused' | 'dropped' | 'override' | 'held' | 'to-grade' | 'not-submitted' | 'not-due' | 'extra-credit' | 'what-if';
export type TraceCode = 'base-score' | 'category-total' | 'course-total' | 'rounding' | 'late-penalty' | 'late-waived' | 'late-over-max' | 'dropped' | 'drop-limited-by-keep' | 'drop-not-beneficial' | 'excused' | 'held' | 'missing-zero' | 'missing-not-droppable' | 'extra-credit' | 'extra-credit-capped' | 'category-empty-shared' | 'override' | 'extension' | 'final-override' | 'not-counted' | 'what-if';
export interface TraceReason { code: TraceCode; params: Record<string, string | number> }
export interface TraceItem { assignmentId: Id; title: string; points: number; raw: number | null; adjusted: number | null; state: CellState; counted: boolean; reasons: TraceReason[] }
export interface TraceCategory { categoryId: Id; name: string; weight: number; effectiveWeight: number; earned: number; possible: number; percent: number | null; contribution: number | null; items: TraceItem[]; reasons: TraceReason[] }
export interface TraceStep { step: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11; code: TraceCode; target: { assignmentId?: Id; categoryId?: Id }; params: Record<string, string | number> }
export interface CalculationTrace { studentId: Id; view: 'student' | 'held'; mode: CalculationMode; rulesVersion: number; setupVersion: number; computedAt: Timestamp; engineVersion: string; categories: TraceCategory[]; steps: TraceStep[]; totals: { weightedEarned: number; weightedPossible: number; percent: number | null; rounded: number | null; letter: string | null; computed: { percent: number | null; rounded: number | null; letter: string | null }; band: { letter: string; min: number; max: number } | null }; reasons: TraceReason[] }
export interface CourseGradeResult { studentId: Id; percent: number | null; letter: string | null; rulesVersion: number; trace: CalculationTrace }
export type SetupCheckCode = 'weights-not-100' | 'weight-invalid' | 'category-empty' | 'drop-exceeds-items' | 'drop-before-complete' | 'keep-at-least-invalid' | 'drop-count-invalid' | 'scheme-gap' | 'scheme-overlap' | 'scheme-order' | 'late-no-cap' | 'extra-credit-uncapped' | 'item-no-category' | 'item-zero-points' | 'missing-droppable' | 'mode-switch-extra-credit';
export interface SetupCheck { code: SetupCheckCode; severity: 'fix' | 'review' | 'pass'; target: string; params: Record<string, string | number>; fixes: { label: string; patch: Partial<GradebookSetup> | { kind: 'open-item'; assignmentId: Id } }[] }
export interface SetupItem { assignmentId: Id; title: string; categoryId: Id | null; points: number; extraCredit: boolean; countsTowardGrade: boolean; status: 'published' | 'scheduled' | 'draft'; dueAt: Timestamp | null; gradedCount: number }
