import { z } from 'zod';
import type { Input, Operation, Output } from '../api';
import * as S from './domain';
const {id,required,string,email,integer,nonnegative,minutes}=S;
const ok=z.object({ok:z.literal(true)});
const pageInput=z.object({limit:integer.min(1).max(200).optional().default(50),cursor:required.optional()});
export const page = <T extends z.ZodType>(schema:T) => z.object({items:z.array(schema),nextCursor:string.nullable()});
const by=<K extends string>(key:K)=>z.object({[key]:id} as Record<K,typeof id>);
const gradeCriteria=S.GradeSchema.shape.criteria;
const userShort=S.UserSchema.pick({id:true,name:true,email:true});
const courseInput=z.object({code:required,title:required,term:required,description:string.optional()});
const assignmentInput=z.object({moduleId:id,title:required,submissionType:z.enum(['text','file','link']),points:nonnegative,dueAt:S.timestamp.nullable().optional()});
const templateInput=z.object({name:required,description:string.optional(),owner:S.TemplateOwnerSchema,modules:z.array(S.TemplateModuleSchema).max(20),tutorDefaults:z.object({lesson:S.TutorModeSchema,assignment:S.TutorModeSchema}),accessFloor:integer.min(0).max(100).nullable()});
const rubricInput=z.object({name:required,version:required.optional(),attribution:string.nullable().optional(),standards:z.array(z.object({number:required,title:required,description:string.optional(),items:z.array(z.object({number:required,text:required,kind:S.RubricCheckKindSchema,check:S.AutomaticCheckSchema.nullable().optional(),criteria:string.optional()})).min(1).max(40)})).min(1).max(40)});
const rubricRef={courseId:id,itemId:id,rubricId:id.optional()};
const activity=z.object({activityKind:z.enum(['lesson','assignment']),activityId:id});
export const OPERATIONS: { [K in Operation]: { input: z.ZodType<Input<K>>; output: z.ZodType<Output<K>> } } = {
 getSession:{input:z.void(),output:z.object({user:S.UserSchema.nullable(),institution:S.InstitutionSchema})},
 signIn:{input:by('userId'),output:z.object({user:S.UserSchema.nullable(),institution:S.InstitutionSchema})},
 signOut:{input:z.void(),output:ok},listDemoUsers:{input:z.void(),output:z.array(S.UserSchema)},resetDemo:{input:z.void(),output:ok},
 updateInstitution:{input:S.InstitutionSchema.pick({name:true,shortName:true,accent:true,setupComplete:true}).partial(),output:S.InstitutionSchema},
 updatePolicy:{input:S.AiPolicySchema,output:S.InstitutionSchema},getOverview:{input:z.void(),output:S.OverviewSchema},
 listUsers:{input:z.object({role:S.RoleSchema.optional()}),output:z.array(S.UserSchema)},
 createUser:{input:z.object({name:required,email,role:S.RoleSchema}),output:S.UserSchema},
 importUsers:{input:z.object({csv:required}),output:z.object({created:z.array(S.UserSchema),errors:z.array(z.object({line:integer.min(1),message:string}))})},
 updateUser:{input:z.object({userId:id,name:required.optional(),role:S.RoleSchema.optional()}),output:S.UserSchema},
 listCourses:{input:z.void(),output:z.array(S.CourseSummarySchema)},createCourse:{input:courseInput.extend({programId:id.nullable().optional(),skipTemplate:z.boolean().optional()}),output:S.CourseSchema},
 getCourseOutline:{input:by('courseId'),output:S.CourseOutlineSchema},
 updateCourse:{input:z.object({courseId:id,code:required.optional(),title:required.optional(),term:required.optional(),description:string.optional(),welcome:string.optional(),outcomes:z.array(required).optional()}),output:S.CourseSchema},
 setCourseInstructors:{input:z.object({courseId:id,userIds:z.array(id)}),output:S.CourseSchema},
 getCourseEnrollments:{input:by('courseId'),output:z.object({userIds:z.array(id)})},setCourseEnrollments:{input:z.object({courseId:id,userIds:z.array(id)}),output:z.object({userIds:z.array(id)})},
 getRoster:{input:by('courseId'),output:z.array(S.RosterEntrySchema)},
 createModule:{input:z.object({courseId:id,title:required}),output:S.ModuleSchema},updateModule:{input:z.object({moduleId:id,title:required.optional(),position:integer.min(0).optional(),objective:string.nullable().optional()}),output:S.ModuleSchema},deleteModule:{input:by('moduleId'),output:ok},
 createLesson:{input:z.object({moduleId:id,title:required,minutes:minutes.optional()}),output:S.LessonSchema},
 updateLesson:{input:z.object({lessonId:id,title:required.optional(),minutes:minutes.optional(),position:integer.min(0).optional(),moduleId:id.optional()}),output:S.LessonSchema},
 deleteLesson:{input:by('lessonId'),output:ok},getLesson:{input:by('lessonId'),output:S.LessonDetailSchema},
 saveBlocks:{input:z.object({lessonId:id,blocks:z.array(S.BlockInputSchema)}),output:S.LessonDetailSchema},
 keepBlock:{input:by('blockId'),output:S.LessonDetailSchema},revertBlock:{input:by('blockId'),output:S.LessonDetailSchema},
 regenerateBlock:{input:z.object({blockId:id,instruction:string.optional()}),output:S.LessonDetailSchema},
 publishLesson:{input:by('lessonId'),output:S.LessonSchema},unpublishLesson:{input:by('lessonId'),output:S.LessonSchema},
 saveProfile:{input:S.LearningProfileSchema.omit({completedAt:true}),output:S.UserSchema},getToday:{input:z.void(),output:S.TodaySchema},
 getStudentLesson:{input:z.object({lessonId:id,version:z.enum(['auto','full']).optional()}),output:S.StudentLessonSchema},answerCheck:{input:z.object({lessonId:id,blockId:id,optionId:id}),output:S.CheckResultSchema},
 setLessonProgress:{input:z.object({lessonId:id,state:z.enum(['in-progress','completed'])}),output:S.LessonProgressSchema},
 listAnnouncements:{input:z.object({courseId:id.optional()}),output:z.array(S.AnnouncementSchema)},
 createAnnouncement:{input:z.object({courseId:id,title:required,body:string,pinned:z.boolean(),publish:z.boolean(),aiDraft:S.ProvenanceSchema.optional()}),output:S.AnnouncementSchema},
 updateAnnouncement:{input:z.object({announcementId:id,title:required.optional(),body:string.optional(),pinned:z.boolean().optional(),publish:z.boolean().optional()}),output:S.AnnouncementSchema},
 deleteAnnouncement:{input:by('announcementId'),output:ok},markAnnouncementRead:{input:by('announcementId'),output:ok},
 draftAnnouncement:{input:z.object({courseId:id,prompt:required}),output:z.object({title:required,body:string,provenance:S.ProvenanceSchema})},
 listBuilderSessions:{input:by('courseId'),output:z.array(S.BuilderSessionSchema)},
 createBuilderSession:{input:z.object({courseId:id,prompt:required,sources:z.array(z.object({name:required,text:string}))}),output:S.BuilderSessionSchema},
 getBuilderSession:{input:by('sessionId'),output:S.BuilderSessionSchema},updateBuilderSession:{input:z.object({sessionId:id,brief:S.CourseBriefSchema.optional(),outline:S.OutlineDraftSchema.optional()}),output:S.BuilderSessionSchema},
 generateOutline:{input:by('sessionId'),output:S.BuilderSessionSchema},generateDrafts:{input:by('sessionId'),output:S.BuilderSessionSchema},
 whoAmI:{input:z.void(),output:z.object({email:email.nullable(),user:S.UserSchema.nullable(),viewingAs:S.UserSchema.nullable()})},
 viewAs:{input:z.object({userId:id.nullable()}),output:z.object({user:S.UserSchema.nullable(),institution:S.InstitutionSchema})},
 listInvitations:{input:pageInput,output:page(S.InvitationSchema)},inviteUser:{input:z.object({name:required,email,role:S.RoleSchema}),output:S.InvitationSchema},
 listApiTokens:{input:z.void(),output:z.array(S.ApiTokenSchema)},createApiToken:{input:z.object({name:required,scopes:z.array(S.ScopeSchema).min(1,'Choose at least one scope.'),expiresInDays:integer.min(1).max(365).optional()}),output:z.object({token:S.ApiTokenSchema,secret:required})},revokeApiToken:{input:by('tokenId'),output:ok},
 listFiles:{input:z.object({courseId:id}).extend(pageInput.shape),output:page(S.FileRecordSchema)},getFile:{input:by('fileId'),output:S.FileRecordSchema},deleteFile:{input:by('fileId'),output:ok},
 getFormats:{input:by('fileId'),output:z.array(S.FormatStatusSchema)},requestFormat:{input:z.object({fileId:id,format:z.enum(['reading','audio','epub','ocr'])}),output:S.FormatStatusSchema},
 getLessonAccess:{input:by('lessonId'),output:S.AccessReportSchema},scanFile:{input:by('fileId'),output:S.AccessReportSchema},getFileAccess:{input:by('fileId'),output:S.AccessReportSchema},
 fixFileIssue:{input:z.object({fileId:id,issueIndex:integer.min(0),fix:z.discriminatedUnion('kind',[z.object({kind:z.literal('alt-text'),element:integer.min(0),alt:string,decorative:z.boolean()}),z.object({kind:z.literal('table-header'),element:integer.min(0)}),z.object({kind:z.literal('metadata'),title:string.optional(),language:required.optional()}),z.object({kind:z.literal('ocr'),language:required.optional()})])}),output:S.AccessReportSchema},
 suggestFix:{input:z.object({target:z.union([z.object({lessonId:id,blockId:id}),z.object({fileId:id,element:integer.min(0)})]),kind:z.enum(['alt-text','rewrite','link-text'])}),output:z.object({suggestion:string,provenance:S.ProvenanceSchema})},
 getCourseAccess:{input:by('courseId'),output:S.CourseAccessReportSchema},getInstitutionAccess:{input:z.void(),output:S.InstitutionAccessReportSchema},exportInstitutionAccess:{input:z.void(),output:z.object({csv:string})},updateAccessPolicy:{input:S.AccessPolicySchema,output:S.InstitutionSchema},
 listAssignments:{input:by('courseId'),output:z.array(S.AssignmentSchema)},
 createAssignment:{input:assignmentInput,output:S.AssignmentSchema},getAssignment:{input:by('assignmentId'),output:S.AssignmentSchema},
 updateAssignment:{input:z.object({assignmentId:id,title:required.optional(),dueAt:S.timestamp.nullable().optional(),points:nonnegative.optional(),submissionType:z.enum(['text','file','link']).optional(),rubric:z.array(S.RubricCriterionSchema.refine(c=>c.levels.length>0,{message:'Each criterion needs at least one level.',path:['levels']}).refine(c=>new Set(c.levels.map(l=>l.id)).size===c.levels.length,{message:'Rubric level ids must be unique.',path:['levels']})).refine(cs=>new Set(cs.map(c=>c.id)).size===cs.length,{message:'Rubric criterion ids must be unique.'}).optional(),position:integer.min(0).optional(),instructions:z.array(S.BlockInputSchema.refine(b=>['heading','text','callout'].includes(b.type),{message:'Assignment instructions support headings, text, and callouts.'})).optional()}),output:S.AssignmentSchema},
 deleteAssignment:{input:by('assignmentId'),output:ok},publishAssignment:{input:by('assignmentId'),output:S.AssignmentSchema},
 listSubmissions:{input:z.object({assignmentId:id}).extend(pageInput.shape),output:page(S.SubmissionSchema.extend({student:userShort}))},
 submit:{input:z.object({assignmentId:id,text:string.optional(),fileId:id.optional(),link:string.optional()}),output:S.SubmissionSchema},getMySubmission:{input:by('assignmentId'),output:S.SubmissionSchema.nullable()},
 gradeSubmission:{input:z.object({submissionId:id,criteria:gradeCriteria,score:nonnegative,feedback:string,feedbackOrigin:z.enum(['human','ai']),feedbackProvenance:S.ProvenanceSchema.nullable().optional()}),output:S.SubmissionSchema},
 draftFeedback:{input:z.object({submissionId:id,criteria:gradeCriteria}),output:z.object({feedback:string,provenance:S.ProvenanceSchema})},releaseGrades:{input:by('assignmentId'),output:ok},
 getGradebook:{input:by('courseId'),output:z.object({assignments:z.array(S.AssignmentSchema.pick({id:true,title:true,points:true,dueAt:true})),rows:z.array(S.GradebookRowSchema)})},exportGradebook:{input:by('courseId'),output:z.object({csv:string})},
 getTutorSetting:{input:activity,output:S.TutorSettingSchema.nullable()},setTutorSetting:{input:S.TutorSettingSchema.omit({setBy:true,setAt:true}),output:S.TutorSettingSchema},startTutorSession:{input:activity,output:S.TutorSessionSchema},
 sendTutorMessage:{input:z.object({sessionId:id,text:required,intent:z.enum(['hint','explain','answer','chat'])}),output:z.object({session:S.TutorSessionSchema,reply:S.TutorMessageSchema})},getTutorSummaries:{input:by('courseId'),output:z.array(S.TutorSummarySchema)},
 listPresets:{input:z.void(),output:z.array(S.PresetSchema)},suggestPreset:{input:z.void(),output:z.object({preset:S.PresetSchema,why:required,provenance:S.ProvenanceSchema.nullable()})},applyPreset:{input:z.object({presetId:S.PresetSchema.shape.id}),output:z.array(S.AdaptationSchema)},listAdaptations:{input:z.void(),output:z.array(S.AdaptationSchema)},undoAdaptation:{input:by('adaptationId'),output:S.AdaptationSchema},
 generateAtScope:{input:z.object({courseId:id,scope:z.object({moduleIds:z.array(id).optional(),lessonIds:z.array(id).optional(),elementTypes:z.array(z.enum(['text','callout','check','document','table','scenario'])).optional(),wholeCourse:z.boolean().optional(),videoScript:z.boolean().optional()}),instruction:string.optional()}),output:z.object({jobId:id})},
 getGenerationJob:{input:by('jobId'),output:z.object({jobId:id,state:z.enum(['running','done','failed']),done:nonnegative,total:nonnegative,lessonIds:z.array(id),error:string.nullable(),failures:z.array(z.object({lessonId:id,type:z.enum(['heading','text','callout','image','check','document','file','video','table','scenario','link']),message:string}))})},
 generateElement:{input:z.object({lessonId:id,type:z.enum(['text','callout','check','document','table','scenario']),instruction:string.optional(),position:integer.min(0).optional()}),output:S.LessonDetailSchema},
 importCourse:{input:z.object({course:courseInput.extend({welcome:string.optional(),outcomes:z.array(required).optional()}),modules:z.array(z.object({title:required,lessons:z.array(z.object({title:required,minutes:minutes.optional(),blocks:z.array(S.BlockInputSchema)}))}))}),output:S.CourseOutlineSchema},
 // ---- Night 3 ----
 listPrograms:{input:z.void(),output:z.array(S.ProgramSchema)},
 createProgram:{input:z.object({name:required,description:string.optional(),templateId:id.nullable().optional(),brand:S.BrandSchema.optional()}),output:S.ProgramSchema},
 updateProgram:{input:z.object({programId:id,name:required.optional(),description:string.optional(),templateId:id.nullable().optional(),brand:S.BrandSchema.optional()}),output:S.ProgramSchema},
 deleteProgram:{input:by('programId'),output:ok},
 setCourseProgram:{input:z.object({courseId:id,programId:id.nullable()}),output:S.CourseSchema},
 listTemplates:{input:z.void(),output:z.array(S.CourseTemplateSchema)},getTemplate:{input:by('templateId'),output:S.CourseTemplateSchema},
 createTemplate:{input:templateInput,output:S.CourseTemplateSchema},updateTemplate:{input:templateInput.partial().extend({templateId:id}),output:S.CourseTemplateSchema},
 deleteTemplate:{input:by('templateId'),output:ok},setInstitutionTemplate:{input:z.object({templateId:id.nullable()}),output:S.InstitutionSchema},
 previewTemplate:{input:z.object({courseId:id,templateId:id.optional()}),output:S.TemplateChangeSetSchema},
 applyTemplate:{input:z.object({courseId:id,templateId:id.optional(),hash:required}),output:S.CourseOutlineSchema},
 listRubrics:{input:z.void(),output:z.array(S.RubricSchema)},getRubric:{input:by('rubricId'),output:S.RubricSchema},
 createRubric:{input:rubricInput,output:S.RubricSchema},updateRubric:{input:rubricInput.partial().extend({rubricId:id}),output:S.RubricSchema},deleteRubric:{input:by('rubricId'),output:ok},
 updateReadinessPolicy:{input:S.ReadinessPolicySchema,output:S.InstitutionSchema},
 getCourseReadiness:{input:z.object({courseId:id,rubricId:id.optional()}),output:S.ReadinessResultSchema},
 runReadinessAi:{input:z.object({courseId:id,rubricId:id.optional(),itemIds:z.array(id).max(100).optional()}),output:S.ReadinessResultSchema},
 reviewFinding:{input:z.object({...rubricRef,decision:z.enum(['accept','dismiss'])}),output:S.ReadinessResultSchema},
 attestItem:{input:z.object({...rubricRef,status:z.enum(['attested','not-applicable']),note:string.max(2000)}),output:S.ReadinessResultSchema},
 clearAttestation:{input:z.object(rubricRef),output:S.ReadinessResultSchema},
 listOutcomes:{input:by('courseId'),output:z.array(S.OutcomeSchema)},
 saveOutcomes:{input:z.object({courseId:id,outcomes:z.array(z.object({id:id.optional(),text:required.max(500)})).max(30)}),output:z.array(S.OutcomeSchema)},
 listOutcomeLinks:{input:by('courseId'),output:z.array(S.OutcomeLinkSchema)},
 setOutcomeLinks:{input:z.object({courseId:id,targetKind:S.AlignableKindSchema,targetId:id,outcomeIds:z.array(id).max(30)}),output:z.array(S.OutcomeLinkSchema)},
 listVariants:{input:by('lessonId'),output:z.array(S.LessonVariantSchema)},
 createVariant:{input:z.object({lessonId:id,audience:S.VariantAudienceSchema}),output:S.LessonDetailSchema},
 getVariantDiff:{input:by('variantId'),output:S.VariantDiffSchema},
 resyncVariant:{input:z.object({variantId:id,blockIds:z.array(id).optional()}),output:S.LessonDetailSchema},
 keepVariant:{input:z.object({variantId:id,blockIds:z.array(id).min(1)}),output:S.LessonDetailSchema},
 listRequirements:{input:z.object({courseId:id.optional()}),output:z.array(S.RequirementSchema)},
 createRequirement:{input:z.object({target:S.RequirementTargetSchema,audience:S.RequirementAudienceSchema,dueAt:S.timestamp.nullable().optional(),recurrence:z.enum(['none','annual']).optional()}),output:S.RequirementSchema},
 updateRequirement:{input:z.object({requirementId:id,dueAt:S.timestamp.nullable().optional(),recurrence:z.enum(['none','annual']).optional()}),output:S.RequirementSchema},
 deleteRequirement:{input:by('requirementId'),output:ok},
 getComplianceReport:{input:pageInput.extend({courseId:id.optional(),status:S.TrainingStatusSchema.optional()}),output:page(S.ComplianceRowSchema)},
 listCompletionEvents:{input:pageInput.extend({courseId:id.optional(),userId:id.optional()}),output:page(S.CompletionEventSchema)},
 exportCompletionEvents:{input:z.object({courseId:id.optional(),since:S.timestamp.optional()}),output:z.object({csv:string})},
 listMyTraining:{input:z.void(),output:z.array(S.RequiredTrainingSchema)},
 getTestOut:{input:by('courseId'),output:S.TestOutSchema.nullable()},
 saveTestOut:{input:z.object({courseId:id,items:S.TestOutSchema.shape.items,passPercent:S.TestOutSchema.shape.passPercent}),output:S.TestOutSchema},
 deleteTestOut:{input:by('courseId'),output:ok},
 getMyTestOut:{input:by('courseId'),output:S.StudentTestOutSchema.nullable()},
 takeTestOut:{input:z.object({courseId:id,answers:z.array(z.object({itemId:id,optionId:id})).max(50)}),output:z.object({passed:z.boolean(),percent:integer.min(0).max(100),certificate:S.CertificateSchema.nullable()})},
 listMyCertificates:{input:z.void(),output:z.array(S.CertificateSchema)},
 getCertificate:{input:by('certificateId'),output:S.CertificateSchema},
 verifyCertificate:{input:z.object({code:required.max(40)}),output:S.CertificateVerificationSchema},
 reissueCertificate:{input:z.object({certificateId:id,learnerName:required.optional()}),output:S.CertificateSchema},
 listReportingLines:{input:z.object({managerId:id.optional(),reportId:id.optional()}),output:z.array(S.ReportingLineSchema)},
 addReportingLine:{input:z.object({managerId:id,reportId:id}),output:S.ReportingLineSchema},
 removeReportingLine:{input:z.object({managerId:id,reportId:id}),output:ok},
 getMyVisibility:{input:z.void(),output:S.MyVisibilitySchema},
 setManagerSharing:{input:z.object({managerId:id,sharing:z.boolean()}),output:S.MyVisibilitySchema},
 getManagerView:{input:z.void(),output:S.ManagerViewSchema}
};
