#!/usr/bin/env node
// Generates mintlify/design-system/tokens.mdx from design/tokens.json, so the docs
// site's token page can't drift from the real values. Mintlify builds straight from
// the repo, so the output is committed. Run after changing design/tokens.json:
//
//   node tools/build_mintlify_tokens.mjs
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(await readFile(join(ROOT, 'design', 'tokens.json'), 'utf8'));
const entries = (group) => Object.entries(group).filter(([k]) => !k.startsWith('$'));
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|');
const swatch = (hex) => `<span style={{display: 'inline-block', width: '1.1em', height: '1.1em', borderRadius: '4px', background: '${hex}', border: '1px solid rgba(0,0,0,.15)', verticalAlign: '-0.2em'}} />`;

const lines = [
  '---',
  'title: "Tokens"',
  'description: "Colors, typefaces, sizes, and radii, generated from the design tokens file."',
  '---',
  '',
  '{/* Generated by tools/build_mintlify_tokens.mjs from design/tokens.json. Do not edit by hand. */}',
  '',
  'Tessera uses one set of design tokens. The screens, the prototype, the component app, and this page all read from the same file, so a token change shows up everywhere.',
  '',
  '<Note>',
  '  The palette is warm paper and ink with **one** teal accent. Violet is reserved for AI content. Warning *text* uses `warning-text`; `warning` is for dots, bars, and icons only.',
  '</Note>',
  '',
  '## Colors',
  '',
  '| | Token | Value | Use |',
  '|---|---|---|---|',
  ...entries(tokens.color).map(([name, t]) => `| ${swatch(t.$value)} | \`${name}\` | \`${String(t.$value).toUpperCase()}\` | ${cell(t.$description)} |`),
  '',
  '## Typefaces',
  '',
  '| Token | Stack | Use |',
  '|---|---|---|',
  ...entries(tokens.font).map(([name, t]) => `| \`${name}\` | ${cell(t.$value.join(', '))} | ${cell(t.$description)} |`),
  '',
  '## Sizes',
  '',
  '| Token | Value | Use |',
  '|---|---|---|',
  ...entries(tokens.size).map(([name, t]) => `| \`${name}\` | ${cell(t.$value)} | ${cell(t.$description)} |`),
  '',
  '## Radii',
  '',
  '| Token | Value | Use |',
  '|---|---|---|',
  ...entries(tokens.radius).map(([name, t]) => `| \`${name}\` | ${cell(t.$value)} | ${cell(t.$description)} |`),
  '',
  '## Density',
  '',
  'Learner surfaces use **comfortable** density: a 15px base, 19px lesson reading at about 68 characters per line, and 44px primary buttons. Instructor and admin surfaces use **compact** density: a 13.5px base, 28–36px controls, and denser tables.',
  '',
];
await writeFile(join(ROOT, 'mintlify', 'design-system', 'tokens.mdx'), lines.join('\n'));
console.log('wrote mintlify/design-system/tokens.mdx');
