import { useState } from 'react';
import { useParams } from 'react-router';
import type { Announcement, Provenance } from '../../../../shared/domain';
import { AiContent, Button, PresenceCard, StatusChip } from '../../components';
import { useApiMutation, useApiQuery } from '../../data/hooks';
import { ErrorNotice, Loading } from '../../shell/Status';
import { usePageTitle } from '../../shell/usePageTitle';
import { CourseBar, Field, Message, dateText } from './common';
import styles from './instructor.module.css';
export function Announcements() {
  const { courseId = '' } = useParams(); usePageTitle('Announcements');
  const q = useApiQuery('listAnnouncements', { courseId }); const course = useApiQuery('getCourseOutline', { courseId });
  const create = useApiMutation('createAnnouncement'); const update = useApiMutation('updateAnnouncement'); const remove = useApiMutation('deleteAnnouncement'); const draft = useApiMutation('draftAnnouncement');
  const [editing, setEditing] = useState<string | null>(null); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [pinned, setPinned] = useState(false); const [prompt, setPrompt] = useState(''); const [aiDraft, setAiDraft] = useState<Provenance | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [fieldError, setFieldError] = useState('');
  const reset = () => { setEditing(null); setTitle(''); setBody(''); setPinned(false); setAiDraft(null); setFieldError(''); };
  const edit = (a: Announcement) => { setEditing(a.id); setTitle(a.title); setBody(a.body); setPinned(a.pinned); setAiDraft(a.provenance); setFieldError(''); requestAnimationFrame(() => document.getElementById('announcement-composer')?.focus()); };
  const run = async (task: () => Promise<unknown>, success: string) => { try { setError(''); await task(); setMessage(success); } catch (e) { setError(e instanceof Error ? e.message : 'Could not complete the action.'); } };
  const editingAnnouncement = q.data?.find(a => a.id === editing);
  const submit = (publish: boolean) => { if (!title.trim() || !body.trim()) { setFieldError('Enter a title and body.'); return; } void (async () => { try { if (editing) await update.mutateAsync({ announcementId: editing, title, body, pinned, publish }); else await create.mutateAsync({ courseId, title, body, pinned, publish, aiDraft: aiDraft ?? undefined }); reset(); setMessage(publish ? 'Announcement published.' : 'Draft saved.'); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save announcement.'); } })(); };
  return <><CourseBar title="Announcements" courseId={courseId} courseTitle={course.data?.course.title} />{course.isPending ? <Loading /> : course.error ? <ErrorNotice error={course.error} onRetry={() => void course.refetch()} /> : <div className={styles.stack}><Message text={message} /><Message text={error} error />
    <section className={styles.panel} id="announcement-composer" tabIndex={-1}><h2>{editing ? 'Edit announcement' : 'New announcement'}</h2><Field label="Title" value={title} onChange={setTitle} error={fieldError && !title.trim() ? 'Enter a title.' : undefined} required /><Field label="Body" value={body} onChange={setBody} error={fieldError && !body.trim() ? 'Enter a body.' : undefined} multiline required /><label className={styles.row}><input type="checkbox" checked={pinned} onChange={e => setPinned(e.target.checked)} /> Pin this announcement</label>{aiDraft && <AiContent kind="note" who="Drafted with AI" source={`${aiDraft.model} · ${editingAnnouncement?.status === 'published' ? 'you edited it before publishing' : 'edit before publishing'}`}>Review the announcement text before saving.</AiContent>}<div className={styles.row}><Button density="compact" onClick={() => submit(false)} disabled={create.isPending || update.isPending}>Save draft</Button><Button variant="primary" density="compact" onClick={() => submit(true)} disabled={create.isPending || update.isPending}>Publish</Button>{editing && <Button density="compact" onClick={reset}>Cancel edit</Button>}</div>
      <h3>Draft with AI</h3><Field label="What should the announcement say?" value={prompt} onChange={setPrompt} /><Button density="compact" disabled={!prompt.trim() || draft.isPending} onClick={() => void (async () => { try { const result = await draft.mutateAsync({ courseId, prompt }); setTitle(result.title); setBody(result.body); setAiDraft(result.provenance); setMessage('AI draft added to the composer. Review and edit it before publishing.'); setError(''); } catch (e) { setError((e as { code?: string }).code === 'ai-disabled' ? 'AI authoring is turned off by the administrator.' : e instanceof Error ? e.message : 'Could not draft announcement.'); } })()}>Draft with AI</Button></section>
    <section><h2>Course announcements</h2>{q.isPending ? <Loading /> : q.error ? <ErrorNotice error={q.error} onRetry={() => void q.refetch()} /> : !q.data?.length ? <p>No announcements yet.</p> : <div className={styles.stack}>{q.data.map(a => <PresenceCard key={a.id} name={a.authorName} initials={a.authorInitials} role="Instructor" time={dateText(a.publishedAt ?? a.createdAt)} dateTime={a.publishedAt ?? a.createdAt} title={a.title} pinned={a.pinned} actions={<div className={styles.row}><StatusChip tone={a.status === 'published' ? 'success' : 'neutral'}>{a.status === 'published' ? 'Published' : 'Draft'}</StatusChip><Button density="compact" onClick={() => edit(a)}>Edit</Button><Button density="compact" onClick={() => void run(() => update.mutateAsync({ announcementId: a.id, publish: a.status !== 'published' }), a.status === 'published' ? 'Announcement unpublished.' : 'Announcement published.')}>{a.status === 'published' ? 'Unpublish' : 'Publish'}</Button><Button density="compact" onClick={() => { if (window.confirm(`Delete announcement “${a.title}”?`)) void run(() => remove.mutateAsync({ announcementId: a.id }), 'Announcement deleted.'); }}>Delete</Button></div>}>{a.origin === 'ai' ? <AiContent kind="note" who="Drafted with AI" source={`${a.provenance?.model ?? 'AI model'} · ${a.status === 'published' ? 'you edited it before publishing' : 'edit before publishing'}`}><p className={styles.preview}>{a.body}</p></AiContent> : <p className={styles.preview}>{a.body}</p>}</PresenceCard>)}</div>}</section></div>}</>;
}
