import { useEffect, useState, type FormEvent } from 'react';
import { useNavigate, useParams } from 'react-router';
import { Button, LessonOutline, StatusNotice } from '../../components';
import { useApiMutation, useApiQuery } from '../../data/hooks';
import { paths } from '../../paths';
import { renderRouterLink } from '../../shell/RouterLink';
import { ErrorNotice, Loading } from '../../shell/Status';
import { usePageTitle } from '../../shell/usePageTitle';
import { ActionLink, CourseBar, Field, Message, SaveButton } from './common';
import styles from './instructor.module.css';

export function Workspace() {
  const { courseId = '' } = useParams(); const navigate = useNavigate();
  const q = useApiQuery('getCourseOutline', { courseId });
  usePageTitle(q.data?.course.title ?? 'Course');
  const updateCourse = useApiMutation('updateCourse'); const createModule = useApiMutation('createModule'); const updateModule = useApiMutation('updateModule'); const deleteModule = useApiMutation('deleteModule'); const createLesson = useApiMutation('createLesson'); const updateLesson = useApiMutation('updateLesson'); const deleteLesson = useApiMutation('deleteLesson');
  const [welcome, setWelcome] = useState(''); const [outcomes, setOutcomes] = useState<string[]>([]); const [moduleTitle, setModuleTitle] = useState(''); const [lessonDraft, setLessonDraft] = useState<Record<string, { title: string; minutes: string }>>({}); const [rename, setRename] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (q.data) { setWelcome(q.data.course.welcome); setOutcomes(q.data.course.outcomes); } }, [q.data?.course.id, q.data?.course.welcome, JSON.stringify(q.data?.course.outcomes)]);
  const run = async (task: () => Promise<unknown>, success: string) => { try { setError(''); await task(); setMessage(success); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save.'); } };
  const modules = q.data?.modules ?? [];
  return <><CourseBar title={q.data?.course.title ?? 'Course'} courseId={courseId} courseTitle={q.data?.course.title} actions={<><ActionLink to={paths.teach.build(courseId)}>Build with AI</ActionLink><ActionLink to={paths.teach.announcements(courseId)}>Announcements</ActionLink><ActionLink to={paths.teach.roster(courseId)}>Roster</ActionLink></>} />
    {q.isPending ? <Loading /> : q.error ? <ErrorNotice error={q.error} onRetry={() => void q.refetch()} /> : <div className={styles.stack}><Message text={message} /><Message text={error} error />
      <section><h2>Course home</h2><form className={styles.inlineForm} onSubmit={(e: FormEvent) => { e.preventDefault(); void run(() => updateCourse.mutateAsync({ courseId, welcome, outcomes }), 'Course home saved.'); }}>
        <Field label="Welcome message" value={welcome} onChange={setWelcome} multiline />
        <div><h3>Outcomes</h3><ul className={styles.list}>{outcomes.map((value, i) => <li key={i} className={styles.row}><Field label={`Outcome ${i + 1}`} value={value} onChange={v => setOutcomes(outcomes.map((x, index) => index === i ? v : x))} /><Button density="compact" onClick={() => setOutcomes(outcomes.filter((_, index) => index !== i))}>Remove</Button></li>)}</ul><Button density="compact" onClick={() => setOutcomes([...outcomes, ''])}>Add outcome</Button></div><SaveButton pending={updateCourse.isPending}>Save course home</SaveButton></form></section>
      <section><h2>Outline</h2><LessonOutline mode="author" renderLink={renderRouterLink} modules={modules.map(m => ({ id: m.id, title: m.title, lessons: m.lessons.map(l => ({ id: l.id, title: l.title, minutes: l.minutes, href: paths.teach.lesson(courseId, l.id), status: l.draftBlockCount ? `${l.draftBlockCount} AI drafts to review` : l.status === 'published' ? 'Published' : 'Draft' })) }))} onMoveModule={(id, direction) => { const i = modules.findIndex(m => m.id === id); void run(() => updateModule.mutateAsync({ moduleId: id, position: i + (direction === 'up' ? -1 : 1) }), 'Module moved.'); }} onMoveLesson={(id, direction) => { const m = modules.find(x => x.lessons.some(l => l.id === id)); if (!m) return; const i = m.lessons.findIndex(l => l.id === id); void run(() => updateLesson.mutateAsync({ lessonId: id, position: i + (direction === 'up' ? -1 : 1) }), 'Lesson moved.'); }} />
      {modules.map(m => <div key={m.id} className={styles.panel}><h3>{m.title}</h3><form className={styles.row} onSubmit={e => { e.preventDefault(); void run(() => updateModule.mutateAsync({ moduleId: m.id, title: rename[m.id] ?? m.title }), 'Module renamed.'); }}><Field label={`Rename ${m.title}`} value={rename[m.id] ?? m.title} onChange={v => setRename({ ...rename, [m.id]: v })} required /><SaveButton pending={updateModule.isPending}>Rename module</SaveButton></form>
        <form className={styles.row} onSubmit={e => { e.preventDefault(); const d = lessonDraft[m.id] ?? { title: '', minutes: '15' }; if (!d.title.trim()) { setError('Enter a lesson title.'); return; } void (async () => { try { const l = await createLesson.mutateAsync({ moduleId: m.id, title: d.title, minutes: Number(d.minutes) }); navigate(paths.teach.lesson(courseId, l.id)); } catch (err) { setError(err instanceof Error ? err.message : 'Could not add lesson.'); } })(); }}><Field label={`New lesson in ${m.title}`} value={lessonDraft[m.id]?.title ?? ''} onChange={v => setLessonDraft({ ...lessonDraft, [m.id]: { title: v, minutes: lessonDraft[m.id]?.minutes ?? '15' } })} required /><Field label="Minutes" type="number" value={lessonDraft[m.id]?.minutes ?? '15'} onChange={v => setLessonDraft({ ...lessonDraft, [m.id]: { title: lessonDraft[m.id]?.title ?? '', minutes: v } })} required /><SaveButton pending={createLesson.isPending}>Add lesson</SaveButton></form>
        {m.lessons.map(l => <div key={l.id} className={styles.row}><span>{l.title}</span><form className={styles.row} onSubmit={e => { e.preventDefault(); void run(() => updateLesson.mutateAsync({ lessonId: l.id, title: rename[l.id] ?? l.title }), 'Lesson renamed.'); }}><Field label={`Rename ${l.title}`} value={rename[l.id] ?? l.title} onChange={v => setRename({ ...rename, [l.id]: v })} /><SaveButton pending={updateLesson.isPending}>Rename</SaveButton></form><Button density="compact" onClick={() => { if (window.confirm(`Delete lesson “${l.title}”?`)) void run(() => deleteLesson.mutateAsync({ lessonId: l.id }), 'Lesson deleted.'); }}>Delete lesson</Button></div>)}
        {m.lessons.length > 0 && <p className={styles.muted}>A module with lessons cannot be deleted. Delete or move its lessons first.</p>}<Button density="compact" onClick={() => { if (window.confirm(`Delete module “${m.title}”?`)) void run(() => deleteModule.mutateAsync({ moduleId: m.id }), 'Module deleted.'); }}>Delete module</Button>
      </div>)}
      <form className={styles.inlineForm} onSubmit={e => { e.preventDefault(); if (!moduleTitle.trim()) { setError('Enter a module title.'); return; } void run(() => createModule.mutateAsync({ courseId, title: moduleTitle }), 'Module added.'); setModuleTitle(''); }}><Field label="New module title" value={moduleTitle} onChange={setModuleTitle} required /><SaveButton pending={createModule.isPending}>Add module</SaveButton></form></section>
    </div>}</>;
}
