import { useEffect, useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router';
import { Button, StatusChip } from '../../components';
import { useApiMutation, useApiQuery } from '../../data/hooks';
import { paths } from '../../paths';
import { ErrorNotice, Loading } from '../../shell/Status';
import { usePageTitle } from '../../shell/usePageTitle';
import { CourseBar, Field, Message, SaveButton } from './common';
import styles from './instructor.module.css';

export function Workspace() {
  const { courseId = '' } = useParams();
  const q = useApiQuery('getCourseOutline', { courseId });
  usePageTitle(q.data?.course.title ?? 'Course');
  const updateCourse = useApiMutation('updateCourse'); const createModule = useApiMutation('createModule'); const updateModule = useApiMutation('updateModule'); const deleteModule = useApiMutation('deleteModule'); const createLesson = useApiMutation('createLesson'); const updateLesson = useApiMutation('updateLesson'); const deleteLesson = useApiMutation('deleteLesson');
  const [welcome, setWelcome] = useState(''); const [outcomes, setOutcomes] = useState<string[]>([]);
  const [moduleTitle, setModuleTitle] = useState(''); const [addingModule, setAddingModule] = useState(false);
  const [addingLesson, setAddingLesson] = useState<string | null>(null); const [lessonDraft, setLessonDraft] = useState<{ title: string; minutes: string }>({ title: '', minutes: '15' });
  const [renaming, setRenaming] = useState<string | null>(null); const [renameTitle, setRenameTitle] = useState('');
  const [deleteNote, setDeleteNote] = useState<string | null>(null);
  const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (q.data) { setWelcome(q.data.course.welcome); setOutcomes(q.data.course.outcomes); } }, [q.data?.course.id, q.data?.course.welcome, JSON.stringify(q.data?.course.outcomes)]);
  const run = async (task: () => Promise<unknown>, success: string) => { try { setError(''); await task(); setMessage(success); return true; } catch (e) { setError(e instanceof Error ? e.message : 'Could not save.'); return false; } };
  const closeRename = (id: string) => { setRenaming(null); requestAnimationFrame(() => document.getElementById(`rename-${id}`)?.focus()); };
  const modules = q.data?.modules ?? [];
  return <><CourseBar title={q.data?.course.title ?? 'Course'} courseId={courseId} courseTitle={q.data?.course.title} />
    {q.isPending ? <Loading /> : q.error ? <ErrorNotice error={q.error} onRetry={() => void q.refetch()} /> : <div className={styles.stack}><p><Link to={paths.teach.template(courseId)}>Template</Link></p><Message text={message} /><Message text={error} error />
      <section><h2>Course home</h2><form className={styles.inlineForm} onSubmit={(e: FormEvent) => { e.preventDefault(); void run(() => updateCourse.mutateAsync({ courseId, welcome, outcomes }), 'Course home saved.'); }}>
        <Field label="Welcome message" value={welcome} onChange={setWelcome} multiline />
        <div><h3>Outcomes</h3><ul className={styles.list}>{outcomes.map((value, i) => <li key={i} className={styles.fieldRow}><Field label={`Outcome ${i + 1}`} value={value} onChange={v => setOutcomes(outcomes.map((x, index) => index === i ? v : x))} /><Button density="compact" onClick={() => setOutcomes(outcomes.filter((_, index) => index !== i))}>Remove</Button></li>)}</ul><Button density="compact" onClick={() => setOutcomes([...outcomes, ''])}>Add outcome</Button></div><SaveButton pending={updateCourse.isPending}>Save course home</SaveButton></form></section>
      <section className={styles.stack}><h2>Outline</h2>{modules.map((m, moduleIndex) => <div key={m.id} className={styles.panel}>
        <div className={styles.outlineHeader}>{renaming === m.id ? <form className={styles.fieldRow} onSubmit={e => { e.preventDefault(); void (async () => { if (await run(() => updateModule.mutateAsync({ moduleId: m.id, title: renameTitle }), 'Module renamed.')) closeRename(m.id); })(); }}><Field label="Module title" value={renameTitle} onChange={setRenameTitle} required /><SaveButton pending={updateModule.isPending}>Save</SaveButton><Button density="compact" onClick={() => closeRename(m.id)}>Cancel</Button></form> : <h3>{m.title}</h3>}
          <div className={styles.row}><Button id={`rename-${m.id}`} density="compact" onClick={() => { setRenaming(m.id); setRenameTitle(m.title); }}>Rename</Button><Button density="compact" disabled={moduleIndex === 0} onClick={() => void run(() => updateModule.mutateAsync({ moduleId: m.id, position: moduleIndex - 1 }), 'Module moved.')}>Move up</Button><Button density="compact" disabled={moduleIndex === modules.length - 1} onClick={() => void run(() => updateModule.mutateAsync({ moduleId: m.id, position: moduleIndex + 1 }), 'Module moved.')}>Move down</Button><Button density="compact" onClick={() => { if (m.lessons.length) { setDeleteNote(m.id); return; } if (window.confirm(`Delete module “${m.title}”?`)) void run(() => deleteModule.mutateAsync({ moduleId: m.id }), 'Module deleted.'); }}>Delete</Button></div>
        </div>{deleteNote === m.id && <p className={styles.muted}>Remove its lessons first.</p>}
        {m.lessons.length > 0 && <ul className={styles.lessonList}>{m.lessons.map((l, lessonIndex) => <li key={l.id} className={styles.lessonRow}><Link to={paths.teach.lesson(courseId, l.id)}>{l.title}</Link><span className={styles.muted}>{l.minutes} {l.minutes === 1 ? 'minute' : 'minutes'}</span><StatusChip tone={l.draftBlockCount ? 'accent' : l.status === 'published' ? 'success' : 'neutral'}>{l.draftBlockCount ? `${l.draftBlockCount} AI ${l.draftBlockCount === 1 ? 'draft' : 'drafts'} to review` : l.status === 'published' ? 'Published' : 'Draft'}</StatusChip><div className={styles.row}><Button density="compact" disabled={lessonIndex === 0} onClick={() => void run(() => updateLesson.mutateAsync({ lessonId: l.id, position: lessonIndex - 1 }), 'Lesson moved.')}>Move up</Button><Button density="compact" disabled={lessonIndex === m.lessons.length - 1} onClick={() => void run(() => updateLesson.mutateAsync({ lessonId: l.id, position: lessonIndex + 1 }), 'Lesson moved.')}>Move down</Button><Button density="compact" onClick={() => { if (window.confirm(`Delete lesson “${l.title}”?`)) void run(() => deleteLesson.mutateAsync({ lessonId: l.id }), 'Lesson deleted.'); }}>Delete</Button></div></li>)}</ul>}
        {addingLesson === m.id ? <form className={styles.fieldRow} onSubmit={e => { e.preventDefault(); void (async () => { if (await run(() => createLesson.mutateAsync({ moduleId: m.id, title: lessonDraft.title, minutes: Number(lessonDraft.minutes) }), 'Lesson added.')) { setAddingLesson(null); setLessonDraft({ title: '', minutes: '15' }); } })(); }}><Field label="Lesson title" value={lessonDraft.title} onChange={title => setLessonDraft({ ...lessonDraft, title })} required /><Field label="Minutes" type="number" value={lessonDraft.minutes} onChange={minutes => setLessonDraft({ ...lessonDraft, minutes })} required /><SaveButton pending={createLesson.isPending}>Add</SaveButton><Button density="compact" onClick={() => setAddingLesson(null)}>Cancel</Button></form> : <Button variant="text" density="compact" className={styles.startButton} onClick={() => { setAddingLesson(m.id); setLessonDraft({ title: '', minutes: '15' }); }}>Add lesson</Button>}
      </div>)}
      {addingModule ? <form className={styles.fieldRow} onSubmit={e => { e.preventDefault(); void (async () => { if (await run(() => createModule.mutateAsync({ courseId, title: moduleTitle }), 'Module added.')) { setAddingModule(false); setModuleTitle(''); } })(); }}><Field label="Module title" value={moduleTitle} onChange={setModuleTitle} required /><SaveButton pending={createModule.isPending}>Add</SaveButton><Button density="compact" onClick={() => setAddingModule(false)}>Cancel</Button></form> : <Button density="compact" className={styles.startButton} onClick={() => setAddingModule(true)}>Add module</Button>}</section>
    </div>}</>;
}
